### ISSUE TITLE
Resource labels appearing very inconsistently

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Rodan#1001]
When using an OMR workflow, the user can connect any number of job outputs to the Labeler job. The resources created by the workflow should then all have whatever label the user gave it. However, these labels show up very inconsistently, and make searching by labels almost impossible. 

Demo: In the workflow run, you can see that of the six resources connected to the Labeler job, only three have a label, even though all six should have the same. When I go to the Resources list and find those same resources, the labels take a while to load, and when they do, they're still not all there. When I try to search by label, the label I want (110v trial 8) isn't one of the options.

https://github.com/DDMAL/Rodan/assets/83373378/361c628e-eed1-4bba-8211-6c86fcf9b831

To reproduce:
1. Make an OMR workflow with several jobs;
2. Connect the output of each job to a Labeler input port and give the Labeler a nifty name;
3. When the workflow is done running, search for the newly created resources in the Resources list;
4. Behold whether or not the label shows up (and how long it takes to do so).

**Comment by jackyyzhang03** [comment]
This might be fixed by PR #915. Previously labels were loaded one by one for each resource, so they would take a very long time to show up, if at all. Could you see if this still happens in staging?

**Comment by JoyfulGen** [comment]
I'll close this issue because rodan has changed a lot since I wrote it! Labels appear very consistently next to their resources now, but searching by label is still a problem. I've detailed that here: https://github.com/DDMAL/Rodan/issues/1127.
