### ISSUE TITLE
Rodan Production is Down Again - rodan-main crashing on startup

### ISSUE THREAD

**Issue by timothydereuse** [DDMAL/Rodan#1054]
As of Aug 10, The rodan-main container starts up and crashes. The images worked fine last week so it's something we've changed recently. I don't know if this is related to the network architecture changes, though I fear it might be.

**Comment by sabrina0822** [comment]
A quick update on this, from what I understand there were some changes to the network architetcure made on both staging and production that caused them both to go down. @timothydereuse was able to get production back up and fixed the certificates. 

As for staging, I'm currently trying to get the new images @kqct has made for her docker cleanup PR (as they should work with the changes to the network architecture), however I'm currently getting this error. when running /run/start: 
```
+ /run/setup
+ chown -R www-data:www-data /var/www/default
+ find /var/www/default -type d
+ xargs chmod 755
+ find /var/www/default -type f
+ xargs chmod 644
+ nginx
2023/08/14 15:51:51 [emerg] 22#22: host not found in upstream "iipsrv" in /etc/nginx/sites-available/rodan.conf:15
nginx: [emerg] host not found in upstream "iipsrv" in /etc/nginx/sites-available/rodan.conf:15
```
