### ISSUE TITLE
Rodan staging: input port windows out of alignment

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Rodan#1094]
On rodan staging, I have a complete e2e workflow set up. If I click on an input port to add resources to it, the window opens, but it's too zoomed in, so I can't see it all. Like so:

<img width="1440" alt="staging input window wacky" src="https://github.com/DDMAL/Rodan/assets/83373378/db4d65b6-8f68-4987-8315-e0deae146c29">

I can't use my trackpad or my mouse to move around the window, so I also can't close it. The only way to get back to the workflow is to reload the page.

I think this has to do with the resource names being longer than the window width. The text alignment resources all have very short names and the window looks fine:

<img width="1191" alt="staging TA ok" src="https://github.com/DDMAL/Rodan/assets/83373378/afc5df34-9425-4afb-b34a-f101dd0bbb6f">

**Comment by softcat477** [comment]
Resolved in #1105
