### ISSUE TITLE
Staging/New UI: Register account and Reset Password does not work

### ISSUE THREAD

**Issue by malajvan** [DDMAL/Rodan#1096]
When trying to create a new account or reset a password, Rodan doesn't actually send an email for confirmation and verification.

Moreover, after successfully changing the password through the Django admin page, if one tries to log in again, they will see instead the pop-up below when entering the correct password. 
![image](https://github.com/DDMAL/Rodan/assets/64571718/e85dd23c-696f-4679-9f4e-b504fb2f8461)

If one enters the incorrect password, they get the usual pop-up:
![image](https://github.com/DDMAL/Rodan/assets/64571718/3ea89072-8c33-46a8-9b46-6d1b5edb138f)

**Comment by softcat477** [comment]
Resolved by setting env variables:

    EMAIL_HOST: Set to the corresponding entry from the AWS Email section of the Resources page on the DDMAL wiki.
    EMAIL_PORT: Set to the corresponding entry from the AWS Email section of the Resources page on the DDMAL wiki.
    EMAIL_HOST_USER: Set to the corresponding entry from the AWS Email section of the Resources page on the DDMAL wiki.
    EMAIL_HOST_PASSWORD: Set to the corresponding entry from the AWS Email section of the Resources page on the DDMAL wiki.
