### ISSUE TITLE
Where does rodan documentation exist?

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Rodan#1129]
There exists this complete rodan tutorial http://ddmal.music.mcgill.ca/e2e-omr-documentation/. It covers all the steps for using rodan quite clearly. I kept that link from when I first was introduced to rodan, but I have no idea where it exists now. Where can it be accessed from? Could a path to it be added in rodan?

**Comment by kyrieb-ekat** [comment]
Update, found the following link points to them- https://ddmal.music.mcgill.ca/software/ when you click "Rodan".

**Comment by kyrieb-ekat** [comment]
User documentation now lives on the wiki for the e2e documentation [here](https://github.com/DDMAL/e2e-omr-resources/wiki), with beginner and advanced reference now also referenced in [Rodan's wiki](https://github.com/DDMAL/Rodan/wiki).

**Comment by kyrieb-ekat** [comment]
Interesting! I will reupload and see if the affected images show up– images in section 6 are coming through fine, fortunately.

**Comment by kyrieb-ekat** [comment]
@fujinaga everything should be fixed now- it was a wonky setting on my end.
