### ISSUE TITLE
On Rodan staging, in the add/remove resources window, 1/3 of view cannot be viewed

### ISSUE THREAD

**Issue by kyrieb-ekat** [DDMAL/Rodan#1146]
See video; scrolling does not help in accessing the needed areas, nor does zooming in/out. This is using the staging server on rodan.staging.simssa.ca

Marked as low priority because I'm uncertain if this issue exists on rodan2 (etc.)

https://github.com/DDMAL/Rodan/assets/74431986/cefce0d0-d020-4456-a9be-4a80bec77192

**Comment by homework36** [comment]
I have the same issue on both staging and production (probably because both use the same nightly built rodan-client image)
