### ISSUE TITLE
While classifying in the IC, a login box appears and will only disappear for a few seconds at a time

### ISSUE THREAD

**Issue by kyrieb-ekat** [DDMAL/Rodan#1154]
Video shows the issue. Using the staging server, in chrome. 

Essentially, when you open the interactive classifier you will be prompted with a login box. If you input your credentials it disappears and immediately reappears. If you hit cancel you gain about five seconds before it reappears. In the past this has happened when copying an error code, see #1147 . 

https://github.com/DDMAL/Rodan/assets/74431986/875ef95a-815f-440c-91a1-299ccc82f3a7

**Comment by homework36** [comment]
Have this when starting Rodan (develop branch) locally as well. Still trying to find where it comes from.
![Screenshot 2024-05-29 at 12 46 10 PM](https://github.com/DDMAL/Rodan/assets/70364944/735ee8f9-7d2a-42ca-9932-b2adaf4b1a0b)

**Comment by homework36** [comment]
Found the related old PR #1076

**Comment by homework36** [comment]
<img width="325" alt="Screenshot 2024-05-31 at 5 25 43 PM" src="https://github.com/DDMAL/Rodan/assets/70364944/3e69b123-0031-416b-a4cc-39e1d4fd12d6">

The new Rodan prod (which is supposed to function properly) is having the same issue! It didn't happen before, even though I basically replicated exactly the same steps when setting up everything 🥀🥀🥀

**Comment by homework36** [comment]
I tried on the old mac mini I used to debug Rodan earlier and with latest codes but images from 4 months ago, there is no popup window issue at all. But we did not have much change to backend since my last commit. I guess it might be a network issue between containers.
```
ddmal/iipsrv                      nightly        dd41d2f70774   4 months ago    21.5MB
ddmal/nginx                       nightly        4d9ae548e0ac   4 months ago    213MB
ddmal/postgres-plpython           nightly        eb22c4407980   4 months ago    575MB
ddmal/rodan-gpu-celery            nightly        5731084bd3e9   4 months ago    7.27GB
ddmal/rodan-client                nightly        cb9ea3495cce   4 months ago    50.5MB
ddmal/rodan-main                  nightly        8d2df5ae8d7d   4 months ago    10.1GB
ddmal/rodan-python3-celery        nightly        aa2daa7fb6fb   4 months ago    7.61GB
redis                             alpine         287766fc4fcf   4 months ago    41MB
rabbitmq                          alpine         e518f1524750   4 months ago    136MB
```

**Comment by homework36** [comment]
> <img alt="Screenshot 2024-05-31 at 5 25 43 PM" width="325" src="https://private-user-images.githubusercontent.com/70364944/335732543-3e69b123-0031-416b-a4cc-39e1d4fd12d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NDY1MTEsIm5iZiI6MTcxNzU0NjIxMSwicGF0aCI6Ii83MDM2NDk0NC8zMzU3MzI1NDMtM2U2OWIxMjMtMDAzMS00MTZiLWE0Y2MtMzllMWQ0ZmQxMmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDAwMTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMjFhNTQ1OGJhYWYyYjY5ZDAyYzkzNTZhNzRhODAyZjJjNzE3ODNmMDYyNDJkY2UxNGVhZmViN2EwOTliN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jR2e2ttaPzbTl3kxTeDu7vEeCByc_pz-CF-c9R9Rot8">
> The new Rodan prod (which is supposed to function properly) is having the same issue! It didn't happen before, even though I basically replicated exactly the same steps when setting up everything 🥀🥀🥀
> 
> It looks like a serious problem with both staging (develop) and production (master)!!! If anyone has any idea please let me know 🙏🙏🙏
> 
> One message from nginx container that seems related:
> 
> ```
> rodan_nginx.1.332fayd5ur38@prod-rodan-swarm-debian    
> 2024/05/31 17:54:16 [warn] 423#423: *1273 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/3/08/0000000083 while reading upstream, client: 10.0.0.2, server: , 
> request: "GET /rodan_client.min.js HTTP/1.0", upstream: "http://10.0.1.20:80/rodan_client.min.js", 
> host: "rodan2.simssa.ca", referrer: "https://rodan2.simssa.ca/"
> ```
> 
> Update: I have no issue using Safari but have this popup window constantly on chrome.



> <img alt="Screenshot 2024-05-31 at 5 25 43 PM" width="325" src="https://private-user-images.githubusercontent.com/70364944/335732543-3e69b123-0031-416b-a4cc-39e1d4fd12d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NDY1MTEsIm5iZiI6MTcxNzU0NjIxMSwicGF0aCI6Ii83MDM2NDk0NC8zMzU3MzI1NDMtM2U2OWIxMjMtMDAzMS00MTZiLWE0Y2MtMzllMWQ0ZmQxMmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDAwMTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMjFhNTQ1OGJhYWYyYjY5ZDAyYzkzNTZhNzRhODAyZjJjNzE3ODNmMDYyNDJkY2UxNGVhZmViN2EwOTliN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jR2e2ttaPzbTl3kxTeDu7vEeCByc_pz-CF-c9R9Rot8">
> The new Rodan prod (which is supposed to function properly) is having the same issue! It didn't happen before, even though I basically replicated exactly the same steps when setting up everything 🥀🥀🥀
> 
> It looks like a serious problem with both staging (develop) and production (master)!!! If anyone has any idea please let me know 🙏🙏🙏
> 
> One message from nginx container that seems related:
> 
> ```
> rodan_nginx.1.332fayd5ur38@prod-rodan-swarm-debian    
> 2024/05/31 17:54:16 [warn] 423#423: *1273 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/3/08/0000000083 while reading upstream, client: 10.0.0.2, server: , 
> request: "GET /rodan_client.min.js HTTP/1.0", upstream: "http://10.0.1.20:80/rodan_client.min.js", 
> host: "rodan2.simssa.ca", referrer: "https://rodan2.simssa.ca/"
> ```
> 
> Update: I have no issue using Safari but have this popup window constantly on chrome.

This is related to `postgre` error `LOG:  incomplete startup packet`
