### ISSUE TITLE
Cannot scroll on staging (jobs, inputs/outputs)

### ISSUE THREAD

**Issue by kyrieb-ekat** [DDMAL/Rodan#1156]
Video below comparing staging and production. 

On staging, can't scroll down to outputs/more input ports. Also affects adding jobs (can't scroll beneath window). Jobs can be searched, inputs/outputs can be accessed beneath the window. 

https://github.com/DDMAL/Rodan/assets/74431986/49dd8eb4-0754-4c45-aac5-5215d609b6e8

**Comment by homework36** [comment]
<img width="502" alt="Screenshot 2024-05-31 at 5 33 22 PM" src="https://github.com/DDMAL/Rodan/assets/70364944/0b7e55d8-9a56-45f3-86ed-9e729f5a1b69">

The `about` on home page also doesn't scroll (this is prod but I guess it's the same for staging)
