### ISSUE TITLE
Batch downloading doesn't work 

### ISSUE THREAD

**Issue by kyrieb-ekat** [DDMAL/Rodan#1180]
Selecting a group of files and then downloading produces a download error, "Archive.zip, site wasn't available". 

https://github.com/DDMAL/Rodan/assets/74431986/b7edc335-c698-414e-8e28-1d786cfe5deb

**Comment by kyrieb-ekat** [comment]
Upgraded priority level because shortly we'll be batch processing ~100 images to classify and then hopefully pull around 500 total clefs from those images; ideally we'll be able to batch download them, or be able to an an optional ZIP output to the 'extract c-clefs' job. @homework36 @lucasmarchd01

**Comment by homework36** [comment]
Does [create_archive](https://github.com/DDMAL/Rodan/blob/0a247013a7b702f2aacf0fc77f31b6e86f42ae5c/rodan-main/code/rodan/jobs/core.py#L946C1-L979C29) work?

**Comment by kyrieb-ekat** [comment]
So, it will try and do it but it looks like it doesn't write all the way, if that makes sense? Screenshot of error attached when I try to bulk download with that, etc. 
![Screenshot 2024-07-17 at 12 15 06 PM](https://github.com/user-attachments/assets/470f00a1-5c5a-4467-a6ec-7a1ca79e2956)

**Comment by homework36** [comment]
I just saw `Note: multi-selecting resources is still experimental.` maybe it's a problem with multi-selecting instead of multi downloading? I will have to experiment and find out.
