### ISSUE TITLE
Layer models produce layers with horizontal or vertical lines (or both!)

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Rodan#1211]
@fujinaga this is the issue for Paco!

The lines are usually extracted from the background and added to one of the layers, or vice versa. They look like this (in these examples, the lines are created by pixels missing in layer 1):

<img width="552" alt="Grid in layer 1" src="https://github.com/user-attachments/assets/91c67025-0ae6-4d35-bde4-7cccc8502d19">

@kyrieb-ekat made models that produce these lines systematically:
[Produces grid - Model 1.zip](https://github.com/user-attachments/files/17097884/Produces.grid.-.Model.1.zip)
[Produces grid - Background model.zip](https://github.com/user-attachments/files/17097916/Produces.grid.-.Background.model.zip)

This is the workflow required to reproduce the issue:
[Fast.json](https://github.com/user-attachments/files/17098041/Fast.json)

Here's an image to reproduce the issue with:
[B&W alphabet.png.zip](https://github.com/user-attachments/files/17098072/B.W.alphabet.png.zip)

@kyrieb-ekat's issue has more resources and info if needed: https://github.com/DDMAL/Rodan/issues/1209

**Comment by homework36** [comment]
This should have been fixed by #1218
