### ISSUE TITLE
Integrate RKDiva View for zooming images

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/Rodan#158]
Currently we only have the ability to see smaller thumbnails for results images. This makes it difficult to see a detailed view of what the job has produced.

To fix this we should have a quick-look-style image preview for image results in the Results pane. When viewing results, a user should be able to select a page (or all pages) and hit space-bar. This will open a window showing the full-quality image.

To make this happen a number of things need to happen:

-- The Diva viewer should be integrated into Rodan.
-- When each job finishes we should have it run the "To JPEG2000" job. This will act like thumbnailing, producing a Diva-prepared JPEG 2000 image that will reside in the "thumbnails" directory for each job.
-- Build a space-bar activated window view using the RKDiva (RodanKit) Window that can take in a single page or a list of pages to view.

This also requires a functioning IIP Image Server.

I'll assign it to myself until we get someone to take the task. It would be nice to have this by the Salzinnes Demo.

**Comment by lingxiaoyang** [comment]
We've integrated diva.js. Closing.
