### ISSUE TITLE
Job required: Gatos binarization (Steps required for Gatos Threshold binarization)

### ISSUE THREAD

**Issue by timwilfong** [DDMAL/Rodan#225]
In order to do the Gatos Threshold binarization method, there are multiple images needed. Currently, there is no way to do this in a single workflow in Rodin. Here are the steps currently needed to run the algorithm in Gamera:

Images required to begin:
- greyscale image
- previously binarization of image using another algorithm (Rodin should allow user to select a binarization method)

1. gatos_background of greyscale image
--needs previous binarization

2. gatos_threshold of original greyscale image
--needs gatos_background file
--needs previous binarization

For example, see code used below:
```python
>>> image0 = load_image(r"/Users/timwilfong/Documents/St_Gallen_Local/PNG/0390/csg-0390_014.png")
>>> 
>>> djvu0 = image0.djvu_threshold(0.2, 512, 64, 2)
>>> 
>>> greyscale0 = image0.to_greyscale()
>>> 
>>> greyscale0.display("greyscale0")
<ImageFrame Window>
>>> 
>>> gatosbackground0 = greyscale0.gatos_background(djvu0, 15)
>>> 
>>> gatosbackground0.display("gatosbackground0")
<ImageFrame Window>
>>> 
>>> gatosthreshold0 = greyscale0.gatos_threshold(gatosbackground0, djvu0, 0.6, 0.5, 0.8)
```

**Comment by lingxiaoyang** [comment]
It seems we don't have this Gatos job right now? Anyway, removing it from 1.0.0 milestone as it's not related to core system.

**Comment by mrbannon** [comment]
This is a job package issue, not Rodan.

**Comment by brandonmpetty** [comment]
I realize this is a closed issue, but I wanted to share that I am working on a Gatos implementation in C++ if you are ever interested in looking at someone else's implementation.  I think this will be the first publicly available implementation of the algorithm, at least that I have seen.  I hope to get it in a releasable state shortly.  One last comment, the description seems to stop at "thresholding."  Gatos is a binarization workflow that also does shrink and swell post processing steps.  It also describes two thresholding implementations, a basic one and then one that does upsampling.  If you are ever interested in adding Gatos support in the future, I hope this could help.

https://github.com/brandonmpetty/Doxa/blob/master/Binarization/GatosWorkflow.hpp
