### ISSUE TITLE
File sharing across celery nodes

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#259]
ref #235 

File sharing across nodes does not work with the celery slaves.  A file's owner:group is tied to the particular node that created the file and cannot be accessed by other nodes.

**Comment by lingxiaoyang** [comment]
Solved in 1ded04c581eb569a00cf9f9b37bccfd50e1c8bb2 d6fe9fc64d8817725b8853b3708d53115205bdef and 47a320040137becfe083cac83605bdd25fa595a6. Closing.
