### ISSUE TITLE
Branching Workflows

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/Rodan#283]
Workflows should be able to split at any given point, creating branches in which a single result can be sent to two (or more) different processing paths. 

Architecturally this shouldn't need too much jigging. To implement this we would just need to set two (or more) jobs to accept the output result of one job. 

I haven't yet evaluated how much this would affect the Celery queue system. I suspect some code will need modification.

This may be related to #218 in ways that will become clear later.

**Comment by lingxiaoyang** [comment]
Fixed in new workflow model. Closing.
