### ISSUE TITLE
Deprecation in page upload

### ISSUE THREAD

**Issue by ahwitz** [DDMAL/Rodan#285]
In the page view, a field reference is deprecated.

rodan/rodan/views/page.py:79: DeprecationWarning: Using `HyperlinkedIdentityField` without including the request in the serializer context is deprecated. Add `context={'request': request}` when instantiating the serializer.
  d = PageSerializer(page_obj).data

rodan/rodan_env/lib/python2.7/site-packages/rest_framework/serializers.py:501: DeprecationWarning: Using `HyperlinkedRelatedField` without including the request in the serializer context is deprecated. Add `context={'request': request}` when instantiating the serializer.
  self._data = self.to_native(obj)

rodan/rodan_env/lib/python2.7/site-packages/rest_framework/serializers.py:306: DeprecationWarning: Using `HyperlinkedIdentityField` without including the request in the serializer context is deprecated. Add `context={'request': request}` when instantiating the serializer.
  value = field.field_to_native(obj, field_name)

**Comment by lingxiaoyang** [comment]
`Page` was removed in current dev Rodan. Closing.
