### ISSUE TITLE
New Workflow Design

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/Rodan#290]
I'm filing this one here for discussion. Please feel free to add your thoughts.

I think I've come up with a way to support both split workflows, as well as multiple inputs and outputs for a single job. This will take a bit of re-engineering of the workflow running process.

The key would be changing the `Job`, `WorkflowJob`, and `RunJob` models to accommodate the following:

 * Instead of a single input/output object, a Job contains an array of input and output description objects, each enumerated (input/output 1, input/output 2, etc.)
 * Instead of a One-to-one relationship between a `RunJob` and a `Result` object, we change this to a one-to-many relationship.
 * We add the number of the output port to each Result object. This could be on the Result object, or we could add an intermediary table between `RunJob` and `Result` containing information about the ordering of the `Result.` Haven't decided on this yet.
 * To the `RunJob` object we add a `previous` (added by @ahwitz already, I think) as well as a `next` field. These are one-to-many FKs to previous and next `RunJob` objects.
 * In addition to `previous` and `next` FKs we also add the output port to which they are assigned. So `RunJob A` has two output ports; `RunJob B` follows `A` attached to `Output 1`, `RunJob C` is attached to `Output 2` of `A`, and so on.
 ** We'll still have to figure out initial and terminal jobs in this situation.
 * When a workflow run is initiated, we create `RunJobs` for each `WorkflowJob` and ensure that their `previous` and `next` objects are assigned.
 * When a workflow is "run" we *don't* immediately add the full list to a Celery chain. Instead, we simply start running the first job in a workflow. 
 * We re-work the task execution system to call on Celery to queue up the `next` object after the current object has finished. This will probably depend on checking to see that all previous jobs have finished executing, because we could end up with the following (possible) workflow:
![wrun](https://f.cloud.github.com/assets/163183/2447987/351d450c-aea0-11e3-8dd1-0c534c2c5286.png)
 * A task is queued up and executed when it is ready. Rather than pre-chaining them, the next task in the workflow is treated as a callback function. Using the same mechanism for waiting for input, we treat a job waiting for a computer to finish processing in the same way as we treat a job waiting for a human to finish processing—that is, it will re-try to run it every so often until it meets the conditions for completion.

Ideas? Thoughts?

**Comment by lingxiaoyang** [comment]
Implemented in current dev Rodan. Closing.
