### ISSUE TITLE
Buggy and slow upload of super high-res images

### ISSUE THREAD

**Issue by timwilfong** [DDMAL/Rodan#298]
I tried uploading multiple super high-res images (200+ MB) for St. Gallen at the same time. I'm happy that there is now a percentage update in the bottom left info bar, but even when it said it was 100% complete, only one image showed on the "Pages" page (image 007), and it doesn't have a file size or display a preview image. I was then able to upload a single page (image 010), which worked, but even then was relatively slow.

If you want to see this, look at the Pages page in the "St. Gallen Super High-Res" project on the new rodan-dev.simssa.ca

ISSUE RECAP:
- Rodan seems incapable of uploading multiple super high-resolution images at the same time, though it doesn't give an actual error message.
- The uploading of these images is very slow. (It's likely just a processing speed issue, but it should be noted anyway.)

**Comment by lingxiaoyang** [comment]
It has been tested that uploading 2~3 high-res images (~170MB) is fine.

For uploading multiple high-res images, client should be responsible to split them into multiple requests, as there should be a limit for size of HTTP request.
