### ISSUE TITLE
Auto Documentation Building

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/Rodan#305]
@rberkow to assist

We should integrate the "readthedocs" GitHub hook and auto-generate documentation on commit. @crantila has done this for `vis`, so he can give us some hints.

**Comment by lingxiaoyang** [comment]
@ahankinson   Is it for client developers to read REST API definitions? We can let developers set up a debug server so that they can check out the docs of REST APIs in the REST framework browsable API. Do we still need `readthedocs` then?

**Comment by ahankinson** [comment]
We can close this for now.
