### ISSUE TITLE
Gamera Classifier re-recognize deleted connected components

### ISSUE THREAD

**Issue by timwilfong** [DDMAL/Rodan#338]
Discussed with Ich: when you delete a connected component in the Gamera classifier, it's gone permanently. You cannot get it back and classify it. It would be ideal if we could draw a box and tell Gamera to redefine all the connected components inside that box, thus giving us back the previously deleted one.

**Comment by lingxiaoyang** [comment]
@timwilfong  @ahankinson  @mrbannon   Was the Gamera classifier a part of Rodan front-end, or did it refer to the original Gamera interface (outside Rodan)?

**Comment by ahankinson** [comment]
You can close this one for now.
