### ISSUE TITLE
Keeping glyphs in classifier but not including them in intelligent searching

### ISSUE THREAD

**Issue by timwilfong** [DDMAL/Rodan#339]
Right now, every time you classify a glyph, it adds it to the classifier and, thus, to the "intelligent" aggregated images used for future classification. Ich would like to add a button where you can take a glyph in the classifier glyphs and, without deleting it, remove it from the group of images whose features are being considered for future classification. (He would also like it visually colour-coded for ease on the eyes.)

**Comment by lingxiaoyang** [comment]
Was the Gamera classifier a part of Rodan front-end, or did it refer to the original Gamera interface (outside Rodan)?

**Comment by mrbannon** [comment]
This is specific to the classification job package.
