### ISSUE TITLE
"Redefine" Workflow (or, maybe better, a Workflow doesn't have to have Resources associated with it to be valid)

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#356]
Right now, a Workflow is valid if all of its input ports are satisfied, which also means that a Workflow MUST have its Resources associated with it prior to running. This creates a restriction on the user; he/she can only reuse a workflow if they use the exact same Resources. 

So, if a user creates Workflow A with Resource set X and then wants to use Resource set Y on the same Workflow, the user must either make a new Workflow B (possibly a duplicate of A) and associate Resource set Y with B, OR modify Workflow A by abandoning the association of Resource set X for Y. Neither option really reuses the Workflow. Rather, a Workflow by this definition is somewhere in between a Workflow and a Workflow Run.

What we want is to change the definition of a Workflow by the following: Resources are NOT associated with the Workflow, and a Workflow CAN have unsatisfied input ports. Naturally, this implies changes to the associated algorithms. It ALSO means that a WorkflowRun is now different; its definition has changed such that it MUST have Resources associated with it that makes input ports satisfied.

This means a fair amount of changes, naturally. Probably best to start with documentation. We should go over details prior to you starting any work.

**Comment by lingxiaoyang** [comment]
Related changes in detail:
- [ ] Remove `ResourceCollection` and `ResourceAssignment`.
- [ ] In workflow validation, an InputPort can have zero or one connection, and there are no other restrictions for InputPorts.
- [ ] In workflowrun creation view, we require an additional parameter in POST data. The data should be a JSON object with InputPort URL as key and list of Resource URLs as value. All unsatisfied InputPorts must be included and there should be at most one list of multiple Resources. The types of the resources must match the InputPorts.
- [ ] The serialization and deserialization logic of workflow needs minor changes.

Doesn't seem to be a lot of work.

**Comment by mrbannon** [comment]
ResourceCollection and ResourceAssignment will still be needed for the
WorkflowRun, right?

**Comment by lingxiaoyang** [comment]
Yes... and no. The input resources are linked through Input objects during workflowrun creation. The issue will be that there needs to be a flag on the originally unsatisfied Input.
