### ISSUE TITLE
Vendor packages should be declared in settings_production.py (or a place other than rodan/jobs/load.py)

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#357]
Currently, vendor packages need to be imported in rodan/jobs/load.py using the module_loader. I think it would be better to not have to modify the Rodan source to add vendor jobs to Rodan.

Instead, could we add a list of vendor packages we want imported within settings_production.py? Whatever the solution, I think the ideal situation is to allow importing of vendor packages to not depend on modification of Rodan source code.

**Comment by ahankinson** [comment]
:+1: 

This can be something like:

```
RODAN_JOBS = [
'rodan.jobs.neon',
'rodan.jobs.gamera'
'...'
]
```

And then in `load.py` it can simply loop through this list and call `module_loader` on the values.

**Comment by mrbannon** [comment]
I was thinking the same thing.

On Tue, Apr 28, 2015 at 10:00 AM, Andrew Hankinson <notifications@github.com

**Comment by mrbannon** [comment]
Although, I prefer the name RODAN_VENDORS or RODAN_JOB_VENDORS to avoid
confusion.

On Tue, Apr 28, 2015 at 10:01 AM, Michael Ryan Bannon <ryan.bannon@gmail.com
> wrote:

> I was thinking the same thing.
>
> On Tue, Apr 28, 2015 at 10:00 AM, Andrew Hankinson <

**Comment by ahankinson** [comment]
"vendor" means "offering something for sale." 

"RODAN_JOB_PACKAGES"?

**Comment by mrbannon** [comment]
Sure.

On Tue, Apr 28, 2015 at 10:04 AM, Andrew Hankinson <notifications@github.com
