### ISSUE TITLE
Get workflowruns associated with project

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#360]
I'd like to see a GET request that take in a Project ID and returns a workflowrun list of only those workflows associated with that Project. This would save overhead of having to get all workflows for the project, then all runs.

Also, might be nice to have a status filter associated with the GET. (E.g. only get finished runs).

**Comment by lingxiaoyang** [comment]
For the first requirement, this will work:
`http://rodan-dev.simssa.ca/workflowruns/?project=206dc2bf32554c609d1a36abbc7e60a3`

**Comment by lingxiaoyang** [comment]
15f6bf389a23cf5ff1a27e98a0d11fbdc96c0a02 adds the status filter:

`http://rodan-dev.simssa.ca/workflowruns/?project=206dc2bf32554c609d1a36abbc7e60a3&status=4`
