### ISSUE TITLE
Gamera job settings key mismatch  " " != "_"

### ISSUE THREAD

**Issue by Ribu** [DDMAL/Rodan#363]
For some Binarization jobs in Gamera, there is a mismatch between the key values of the "job_settings" dictionary whenever the key itself is composed of more than one word (with spaces). 

For instance, when I load a workflow. 

![screen shot 2015-05-28 at 6 02 45 pm](https://cloud.githubusercontent.com/assets/7508527/7872320/1b140ea8-0565-11e5-9842-180d5d00b229.png)

It is validated fine as it respects the settings' dictionaries' indicated key value
![screen shot 2015-05-28 at 6 03 53 pm](https://cloud.githubusercontent.com/assets/7508527/7872325/1cf04796-0565-11e5-9769-3dfbd44abb3f.png)

However, when the job is run, a runtime error is obtained. 
![screen shot 2015-05-28 at 6 01 47 pm](https://cloud.githubusercontent.com/assets/7508527/7872319/1a97ea76-0565-11e5-80ef-857d147f460b.png)

This is due to the fact that the expected key requires an "_" character as opposed to a space, which in turn is contradictory to what is described in the API. Upon further investigation, it was noted that temporary fixes were made by using the following code. 
![screen shot 2015-05-28 at 6 20 35 pm](https://cloud.githubusercontent.com/assets/7508527/7872538/da0675ca-0566-11e5-8cb1-00008977383a.png)

However, it was pointed out by Andrew Hankinson that the real bug resides in the following file 

https://github.com/DDMAL/Rodan/blob/develop/rodan/jobs/gamera/argconvert.py

**Comment by ahankinson** [comment]
Excellent bug report.
