### ISSUE TITLE
Need way of identifying subworkflows

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#365]
Per our discussion, we need a way to reference a workflow within a workflow.

Right now, this is possible via the API. However, the concept of a subworkflow is lost when it is saved to the server; the subworkflow is reduced to its jobs (and associated connections). The concept of a subworkflow needs to be preserved within the model.

**Comment by lingxiaoyang** [comment]
Proposed design A: 

Add models: `WorkflowInputPort` and `WorkflowOutputPort`, as the input/output ports at the `Workflow` level. 

Once a workflow is validated, it cannot be modified anymore, and `WorkflowInputPort`s and `WorkflowOutputPort`s are created, as the "symlinks" of the unsatisfied `InputPort`s and the `OutputPort`s at the end of the workflow. 

A new workflow can have `Connection`s with `WorkflowInputPort`s and `WorkflowOutputPort`s of an existing workflow.

Here are the extensions needed to implement:

Old Model Object  |   New Model Object
------------------------|-----------------------------
`WorkflowJob`        |     `WorkflowJob` or `Workflow`
`InputPort`  | `InputPort` or `WorkflowInputPort`
`OutputPort` | `OutputPort` or `WorkflowOutputPort`
`Connection` | `Connection` (supporting `WorkflowIn/OutputPort`)

This will occur changes in model validation (particularly, the OR relationship of required field), workflow validation, and recursive execution.

**Comment by mrbannon** [comment]
I think this works, except for one issue. I don't believe that a workflow should be locked from modification once validated, although I think I see why you want this - if workflow A is used in workflow B, changing A causes B to break.

Workflow validity should not mean that it's not editable. I could easily imagine a user putting together a workflow and checking its validity while building it, so locking the workflow when valid would not work.

However, we could flag workflows as "read only"...? @ahankinson do you have any thoughts?

**Comment by lingxiaoyang** [comment]
Here's another perspective:

The user doesn't "lock" workflows anymore. Instead, the user **define** the input ports and output ports that the referenced workflow should have. So, no matter how the referenced (lower level) workflow changes, it has no influence on the definition of the user's (upper level) workflow.

I would define a `Subworkflow` model, containing following fields:

 - `workflow`: the upper level workflow (the workflow it belongs to, on the same level of other workflow jobs)
 - `referenced_workflow`: the lower level workflow, could be null value

... and I would define `SubworkflowInputPort` and `SubworkflowOutputPort` models, containing following fields:

 - `subworkflow`: the subworkflow object
 - `description`: user-friendly  (for example, the user would write: "gray image")
 - `input_port` or `output_port`: the related InputPort or OutputPort object, could be null value

... and the `Connection` object needs to be extended.

In this way, from the user's perspective of the upper workflow, there's nothing related with the lower workflow. Even if the lower workflow is deleted, the `Subworkflow`, `SubworkflowInputPort` and `SubworkflowOutputPort` model still exists in the upper workflow.

But the validation needs to go to the lower level. New conditions should be added:

 - the subworkflow should be valid.
 - the referenced `InputPort`s and `OutputPort`s should belong to the subworkflow.
 - `SubworkflowInputPort` and `SubworkflowOutputPort` should be unique regarding the related `InputPort` or `OutputPort`.
 - `SubworkflowInputPort`s should cover all `InputPort`s of the subworkflow.
 - there are common resource types between `SubworkflowInputPort` and its upstream `OutputPort`, and between `SubworkflowOutputPort` and its downstream `InputPort`s.

And the following changes should invalidate an upper workflow (recursively):

 - the deletion of a lower workflow
 - the deletion of a referenced `InputPort` and `OutputPort`
 - the addition of an `InputPort`

How do you think?

**Comment by mrbannon** [comment]
This seems fine to me. @ahankinson, do you have an opinion?

**Comment by lingxiaoyang** [comment]
Had a discussion with @ahankinson .  The concept of subworkflow can also be represented as grouping. The user can drag a workflow into the workflow designer, and although all workflow jobs will be flattened, the user can select, drag and delete them as a whole. Within a workflow job group, the user can modify each job's settings, but cannot change the structure of the group (the deletion of workflow jobs and connections), unless the user ungroups it.

The user can also group connected workflow jobs, and extract them as a separate workflow.

For the implementation, the workflow job model will add a `group` field for distinguishing different groups, and a `source` nullable foreign key field linking back to the source workflow of the group.
