### ISSUE TITLE
Get list of loaded job packages via REST (w/ version number).

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#371]
Currently we can get a list of all jobs installed into Rodan. It would be convenient (for debugging) if we could get a list of all packages, with version numbers for those packages, that are installed in the Rodan server we're connecting to.

**Comment by ahankinson** [comment]
In principle I'm ok with this, but we should do some security due diligence before exposing this to the public. For example, if there are known vulnerabilities in certain versions of packages, it might not be a good idea to expose this to the full public.

Is there a specific use case for this?

**Comment by mrbannon** [comment]
I'd like the client to display some configuration information about the
Rodan instance it is connecting to. I could imagine a user connecting to a
Rodan server that's supposed to be outfitted with the version 1.0.1 (or
whatever) of "package foo", however the client shows that "package foo" is
only at 1.0.0. Suppose 1.0.1 fixes a bug in 1.0.0; the (informed) user
knows what to expect (i.e. buggy foo).

Ryan

PS - Buggy foo sounds hilarious.

On Mon, Jun 29, 2015 at 11:06 AM, Andrew Hankinson <notifications@github.com

**Comment by ahankinson** [comment]
Could we expose this inside of the job itself? So a user can get information about a job, including the packages (with versions) used to implement it.

**Comment by mrbannon** [comment]
I suppose we could. However, what I had in mind was to have an "About"
button that gives the configuration information of the server. That is,
before the user starts inspecting Jobs, they can determine if the
particular config of Rodan meets their needs. This implies that some
summary data about Rodan (e.g. Rodan version, foo version, bar version,
etc.) be exposed after login, without having to fetch the Jobs.

On Mon, Jun 29, 2015 at 11:14 AM, Andrew Hankinson <notifications@github.com

**Comment by ahankinson** [comment]
I would be OK with exposing the version of Rodan on the root end-point (there's a "configuration" object in the response already).

I'm still not sure about exposing the Python package numbers directly in the response, without any context. 

If you have a specific use case that you're working on right now, could you explain it? Maybe then I can know if it make sense to do this.

**Comment by mrbannon** [comment]
I don't have a use case beyond what I've already presented. It's no big
deal, though. It was more for the future, really.

On Mon, Jun 29, 2015 at 11:39 AM, Andrew Hankinson <notifications@github.com

**Comment by lingxiaoyang** [comment]
I'm exposing the package versions in root view now. Let me know if you have further needs, or you would like to restrict the access to them.

**Comment by lingxiaoyang** [comment]
I consider this being implemented in commit fc3537c. The version number is only informative for the client.

**Comment by mrbannon** [comment]
Tx!
