### ISSUE TITLE
Uniform validation error message format (or perhaps uniform error message format in general)

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#372]
Right now a failed workflow validation simply gives a text string describing the error. I believe we need error messages that:

- are ID-coded
- provide more semantic information

For example, if a WorkflowJob does not have an OutputPorts, we might receive the following:

`The WorkflowJob 4e7af311abe64b82ac0a3aba1d1e4e54 has no OutputPorts`
(The actual response is a JSON object with the error string only.)

Instead, what would be great is a JSON object that:

- has an ID
- gives a description of the error (optional)
- provides the URLs of the associated objects that are the cause (or involved) in the error

In the above example, perhaps something like:

`
{
"error_code": "RODAN_ERROR_VALIDATION_0049",
"description": "The WorkflowJob 4e7af311abe64b82ac0a3aba1d1e4e54 has no OutputPorts",
"associated_objects": 
     {
          "workflow_job": "http://foo.bar.com/workflow/4e7af311abe64b82ac0a3aba1d1e4e54"
     }
}
`

"associated_objects" would depend on the error code, naturally.

Furthermore, we may want to have standardized error formatting across the entire spectrum of possible Rodan errors.

**Comment by lingxiaoyang** [comment]
We need to define several error codes: description and arguments. Perhaps a wiki page for them.

**Comment by mrbannon** [comment]
Oh heck yeah!

**Comment by ahankinson** [comment]
The problem with custom-defined error codes is that we then need custom-defined error code handlers in the client.

Can/should this be implemented in the HTTP layer?

**Comment by ahankinson** [comment]
Or, perhaps, at least partially on the HTTP layer? What we want to avoid is a response with an error code returning a 2XX. Validation seems to me like a client issue (the client has requested something that the server cannot do), so returning a 4XX with a body that contains more information (including an internal Rodan error code) would be great.

**Comment by mrbannon** [comment]
Three things to note here:

1) Validation is a server-side process, not a client-side process. Every
time  a change is made to a Workflow, it becomes invalid. The user must
request validation from the server. (This validation check is done
automatically if the user requests a WorkflowRun.)

Since validation is on the server, putting validation on the client side
becomes an unneeded redundancy (for NOW...perhaps not in the future). Also,
it makes sense to keep validation in one place in case a change is made to
the validation algorithm (which, at this point, happens every so often due
to bugs).

That is NOT to say that the client can't have ANY validation. For example,
making sure that a user does not add too many ports to a WorkflowJob is an
easy check.

2) Right now, Rodan returns 4XX on validation errors, since validation
constitutes a PATCH/PUT to a Workflow model.

3) From my POV, error codes are a necessity. A Rodan client is a wrapper
for Rodan functionality, and has the responsibility of exposing information
from the server in a way that is tailored to the user. This includes
displaying errors so that the user can understand them. At the same time,
it is up to the client (or, rather, the client developer) to decide how to
display errors; they could either rely on the default Rodan error detail
information (thus, not needing to process error codes), OR have a custom
error handler that interprets error codes (and any other associated data).
This is why I suggested that the error responses from the server have a
default "detail/message" field along with the error code.

**Comment by ahankinson** [comment]
1) Workflows are constructed by the client, and validation is requested by the client. I'm not saying the client should be doing validation, but we should make sure to return a suitable error code when the client requests validation from the server. Returning 2XX on a failed validation request is not RESTful.

2) I think 4XX are correct. The client has constructed an invalid workflow, so it's not the server's fault.

3) Contextual human-readable error messages are necessary; I'm still trying to be convinced of error code types. You need to notify the user of exactly what went wrong, but just responding with `"RODAN_ERROR_VALIDATION_0049"` is not very helpful. A client can be coded to respond to 4XX error codes and display the message straight from the server.

I'm not saying it's not going to happen; I just don't want Rodan to go down the "PC LOAD LETTER ERR 49" route. (i.e., displaying meaningless error codes without any real explanation).

**Comment by lingxiaoyang** [comment]
The validation process will always return 409 (CONFLICT) when there is an error in workflow. The point is to help the user understand what error has happened and which objects are related.

REST framework is not using internal error codes. For example, there can be multiple reason leading to a 400 response, but the reason is provided in the same response in the format of `{'detail': ....}`. So perhaps we do not need to invent internal error codes for Rodan. 

And at present there is a message for the 409 response of workflow validation, but it is a bit hard for the user to read. I think I'll return an error message in following format:

````
{'detail': 'A WorkflowJob has no OutputPorts',
 'associated_objects': {"workflow_jobs":    ["http://foo.bar.com/workflow/4e7af311abe64b82ac0a3aba1d1e4e54" ]}
}
````

And the client displays the error detail, and highlights all associated objects. Then the client itself does not need to understand the message, but hand it to the user to digest.

**Comment by mrbannon** [comment]
I would still like an error code. In the void client, we would use
different terminology. For example, "analysis" instead of "workflow". But,
more importantly, the client needs some context so it can make sense of the
associated objects returned.

Again, a client site not have to use this, but I think a client should be
privy to exactly what error has occurred.

Also, I have no problem with this being limited to validation.

**Comment by mrbannon** [comment]
Forgot to respond to this...

I agree, HTTP 4XX is for sure the way to go, and that's what it does now.
It's a failed PUT/PATCH if validation doesn't work (as you are requesting a
change to a field in the workflow).

I also agree that contextual, human-readable error messages are necessary.
However, such messages are only useful to the educated Rodan user, not the
client or general user. The client should have the power to interpret an
error and act accordingly. For example, if a WorkflowJob is not valid
because it is missing a particular InputPort of InputPortType X, the
standard message may not be "simple" enough for the user to understand. At
this point, it becomes beneficial to the user if the client knows exactly
what the error is, present the error in a fashion that the user can
understand (e.g. in the vernacular of the user, not of Rodan), and perhaps
offer a suggestion to the user as to how to fix the error (e.g. highlight
the associated objects and provide helpful information to the user). I also
believe this argument applies to localization (if anybody wants to make a
client in French, perhaps...although that's a ways off).

Again, I want to stress that these error codes could be limited to Workflow
validation, so they are beyond the scope of REST. AND, it is up to the
client developer to decide whether to interpret them or not.

**Comment by lingxiaoyang** [comment]
@mrbannon  It makes sense.

**Comment by lingxiaoyang** [comment]
Here are some of the error definitions according to the validation algorithm. Please feel free to comment:

`WFJ_NO_OP`
Description: The WorkflowJob has no OutputPort.
Arguments: `WorkflowJob`

`WFJ_TOO_FEW_IP`
Description: The WorkflowJob has too few InputPorts.
Arguments: `WorkflowJob`

`WFJ_TOO_MANY_IP`
Description: The WorkflowJob has too many InputPorts.
Arguments: `WorkflowJob`

`WFJ_TOO_FEW_OP`
Description: The WorkflowJob has too few OutputPorts.
Arguments: `WorkflowJob`

`WFJ_TOO_MANY_OP`
Description: The WorkflowJob has too many OutputPorts.
Arguments: `WorkflowJob`

`WFJ_INVALID_SETTINGS`
Description: The WorkflowJob has invalid settings.
Arguments: `WorkflowJob`

-------------

`IP_TYPE_MISMATCH`
Description: The InputPortType of InputPort does not belong to the underlying Job of WorkflowJob.
Arguments: `InputPort`

`IP_TOO_MANY_CONNECTIONS`
Description: the InputPort has more than one connections.
Arguments: `InputPort`

-----------

`OP_TYPE_MISMATCH`
Description: The OutputPortType of OutputPort does not belong to the underlying Job of WorkflowJob.
Arguments: `OutputPort`

`NO_COMMON_RESOURCETYPE`
Description: there is no common ResourceType between an OutputPort and connected InputPorts.
Arguments: `OutputPort`, `InputPort1`, `InputPort2`, ..., `InputPortN`

------------

`WF_EMPTY`
Description: Workflow is empty.
Arguments: None

`WF_NOT_CONNECTED`
Description: the Workflow is not connected.
Arguments: None

`WF_HAS_CYCLES`
Description: the Workflow has cycles.
Arguments: `Connection` (that causes the problem)

**Comment by mrbannon** [comment]
Does WP_NOT_CONNECTED mean there are orphan WorkflowJobs?

**Comment by lingxiaoyang** [comment]
@mrbannon   Yes.... or no. A workflow can only contain one workflow job. In that case the workflow is still connected.

**Comment by lingxiaoyang** [comment]
The error format will be:

````
{
    'error_code': 'WF_HAS_CYCLES',
    'details': 'The workflow has cycles.',
    'associated_objects': ['http://xxxx/connection/xxxxxxxxx', ...]
}
````

**Comment by lingxiaoyang** [comment]
...correction of error format:

````
{
    'error_code': 'WF_HAS_CYCLES',
    'details': 'The workflow has cycles.',
    'associated_objects': { 'connections': ['http://xxxx/connection/xxxxxxxxx', ...], 'inputports': [.....]}
}
````

**Comment by mrbannon** [comment]
Tx

**Comment by lingxiaoyang** [comment]
The error definitions and example server return are described here:
https://github.com/DDMAL/Rodan/wiki/New-Workflow-Model---Validation#validation-error-table
