### ISSUE TITLE
Investigate Docker

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/Rodan#374]
We should look at getting Rodan up and running with a Docker setup. 

https://www.docker.com

**Comment by Ribu** [comment]
I will definitely look into it, thanks !

**Comment by lingxiaoyang** [comment]
@ahankinson    I'm considering to use autoconf to configure the example settings files in Rodan, to be easier in bash. Do you have other suggestions of tools that are similar to autoconf?

**Comment by ahankinson** [comment]
not sure what you want to do with autoconf? Could you explain?

**Comment by lingxiaoyang** [comment]
Primarily for settings_production.py, the fields there need manual editing and thus are hard to automate.

Also a bonus for generating nginx/gunicorn/supervisor configurations, provided with arguments such as domain name, virtual environment folder, data folder, etc...

**Comment by ahankinson** [comment]
Propose it as a pull request on a branch and I'll have a look.

**Comment by lingxiaoyang** [comment]
OK

**Comment by lingxiaoyang** [comment]
Related paper on Docker (not necessarily related to the issue itself): http://domino.research.ibm.com/library/cyberdig.nsf/papers/0929052195DD819C85257D2300681E7B/$File/rc25482.pdf
