### ISSUE TITLE
WorkflowJob name field

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#375]
Could you please add a name field for the WorkflowJob model?

**Comment by ahankinson** [comment]
Why? Would a workflow job name ever be different from the job name it's derived from?

**Comment by mrbannon** [comment]
I can think of two reasons:

1) The Job names aren't very reader-friendly. They correspond to the Python
import name.
2) More importantly, it's possible that two WorkflowJobs will exist in a
Workflow that each derive from the same Job. So, a user-defined name would
be useful for the user to differentiate between the two.

Also, it's very easy to do. :)

**Comment by ahankinson** [comment]
But then people will have to provide names for every WorkflowJob...

**Comment by mrbannon** [comment]
No. A default name can exist based on the job name. There's no harm in
giving them the option to customize the name
