### ISSUE TITLE
Update documentation: redis and ws4redis

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#384]
While Redis is mentioned, Rodan's dependency on Redis is not explicit enough. In particular:

- what is Redis
- what is ws4redis

(I can assume what they are, but it's helpful to just give a one-liner for each of these dependencies.) Should should be stated at the top of the "Server" section, along with any installation steps that are required.

**Comment by yihongluo** [comment]
These dependencies have been added, along with a description for psycopg2.
