### ISSUE TITLE
Investigate Phusion Passenger

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/Rodan#385]
https://www.phusionpassenger.com/library/deploy/nginx/deploy/python/

This seems like it would remove the Supervisor FCGI requirement. Probably worth looking into.

Assigning to @lingxiaoyang for now but it may get passed on to someone else.

**Comment by lingxiaoyang** [comment]
Django websocket has a dependency to uWSGI, which Passenger seems to want to replace... otherwise it seems a good replace to supervisor+gunicorn/uWSGI.

**Comment by ahankinson** [comment]
I've looked at Phusion for other projects; I would stick with Gunicorn / uWSGI, etc. for now.
