### ISSUE TITLE
Sorting and filtering required on server

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#386]
Right now Rodan handles pagination on the server side (which is great). However, this makes sorting and filtering on the client end impossible. That is, the sorting and/or filtering is only applied to what the client has, that being the current page.

We can discuss the best way to provide sorting and filtering info to the server.

**Comment by lingxiaoyang** [comment]
We can have sorting+pagination or filtering+pagination. The only problem would be that the server may need to sort or filter every time (but we can tweak the database, like adding index to certain columns).

Yes, the sorting and filtering are impossible at the client side... they always need server to compute, as there may be thousands of rows in the database.

**Comment by lingxiaoyang** [comment]
Example: http://rodan-dev.simssa.ca/runjobs/?status=4&page=3   (after session auth)

**Comment by lingxiaoyang** [comment]
And it is to say, sorting and filtering can only happen on pre-selected columns (it would be too costly if every column in database has index). We also need to somehow bring this information to the client...

**Comment by lingxiaoyang** [comment]
... OPTIONS could be considered.

**Comment by lingxiaoyang** [comment]
@mrbannon    Please let me know a list of fields in each model that you'd like to have ordering or filtering on. I'll add db_index in model definitions and add parameters in views. 

There could be composite fields, like `/resources/?project=xxxx&ordering=-created`. In this case I'll add composite index for both fields.

**Comment by mrbannon** [comment]
@lingxiaoyang If you're around Friday I'd like to discuss this.

**Comment by lingxiaoyang** [comment]
@mrbannon  Sure. I'll be around Friday afternoon.

**Comment by lingxiaoyang** [comment]
We reached an agreement: I'll add db index to all fields with simple data type. And provide filter_fields and ordering_fields in OPTIONS in list views to give the client an idea of filterable and sortable fields.

**Comment by lingxiaoyang** [comment]
... unless there is a big performance impact if all fields are indexed in db.

**Comment by lingxiaoyang** [comment]
@mrbannon  Now OPTIONS of list views gives "filter_fields" and "ordering_fields" such as:

``````
    "filter_fields": {
        "status": [
            "exact"
        ], 
        "project": [
            "exact"
        ], 
        "updated": [
            "lt", 
            "gt"
        ], 
        "uuid": [
            "exact"
        ], 
        "workflow": [
            "exact"
        ], 
        "created": [
            "lt", 
            "gt"
        ], 
        "creator": [
            "exact"
        ], 
        "name": [
            "exact", 
            "icontains"
        ]
    }, 
    "ordering_fields": [
        "status", 
        "updated", 
        "uuid", 
        "workflow", 
        "created", 
        "project", 
        "creator", 
        "name"
    ]
``````

I didn't check all fields -- feel free to raise an issue about a specific field. Generally, the lookup type of uuid-related fields is `exact`, of datetime-related fields is `lt` and `gt`, of name-related fields is `exact` and `icontains`. Usage example:

`````
http://localhost:9001/workflowruns/?status=4
http://localhost:9001/workflowruns/?name__icontains=OMR
`````

Database indices haven't shown any performance impact when testing: 

````
python manage.py test rodan.test.views.test_workflow: 12.932s vs 13.167s
python manage.py test rodan.test.views.test_workflowrun: 24.857s vs 24.468s
````

We'll need to observe it in future production scenarios.

**Comment by lingxiaoyang** [comment]
@mrbannon   And a known change on API: in resource list view, GET parameter `uploaded=True` has been replaced by `origin__isnull=True`.

**Comment by ahankinson** [comment]
Thank you for this very good and thoughtfully-designed change. :+1:
