### ISSUE TITLE
Pagination information

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#387]
When sending a GET request for 'jobs', the pagination info I get includes:

    "count": 8, 
    "next": null, 
    "previous": null, 
    "current_page": 1, 
    "total_pages": 1

That's great! However, for 'resources':

    "count": 59, 
    "next": "http://132.206.14.136/resources/?page=2", 
    "previous": null

The 'current' and 'total' members are missing. Is there a reason for this? If not, can all GET collections include all five members (count, next, previous, current_page, total_page)?

Thanks.

**Comment by ahankinson** [comment]
Job has a rodan-specific paginator: https://github.com/DDMAL/Rodan/blob/develop/rodan/views/job.py#L3

Resource uses the built-in paginator that does not include this count.

**Comment by mrbannon** [comment]
@lingxiaoyang, not all Collections are returning:

"count" 
"next" 
"previous" 
"current_page" 
"total_pages"

For example, look at http://132.206.14.136/inputs/. I need to know the total pages and the current page. Please include all this information on ALL ROUTES (even if there's only one page, please). Tx.

**Comment by lingxiaoyang** [comment]
@mrbannon   Sorry! I thought we only missed one paginator in resource list view. I added the paginator to all views. Let me know if there's still a problem.
