### ISSUE TITLE
Send email notifications to owners of workflow runs

### ISSUE THREAD

**Issue by lingxiaoyang** [DDMAL/Rodan#389]
Optional functionality for Rodan. Investigate Django plugins. Investigate the prerequisites for sending emails to arbitrary email address.

**Comment by ahankinson** [comment]
You might consider doing this as a periodic (every minute?) celery task, just to make sure you don't overload the web application itself in admin jobs.

**Comment by lingxiaoyang** [comment]
Will not be in 1.0.0.

**Comment by mrbannon** [comment]
notifications should include:

- runjob failure
- workflowrun completion
- waiting on input (maybe...?)
