### ISSUE TITLE
Develop Rodan "Stable" Release

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/Rodan#390]
I'd like to start releasing stable Rodan builds. We'll start with 1.0.0 and move on up from there. I've created a new milestone, RELEASE-1.0.0, due on October 31, and have assigned all of the issues to it. @lingxiaoyang could you please go through these issues and either close them or move them to the "Someday" milestone.

Once the issues are cleared and no blockers are filed, then I think we can do the merge-to-master dance and tag it.

**Comment by lingxiaoyang** [comment]
I set the version as `1.0.0-alpha`. The previous requirements should all be fulfilled and unit-tested. Do I push the version to the master branch? (as I'll start working on new functionalities on dev branch.) @ahankinson

**Comment by ahankinson** [comment]
Yes! :+1: I'll create a tag.

**Comment by lingxiaoyang** [comment]
@ahankinson  OK. It's pushed to master.

**Comment by ahankinson** [comment]
Fantastic! Thank you for this.

https://github.com/DDMAL/Rodan/releases/tag/1.0.0-beta
