### ISSUE TITLE
Rodan returning 500 errors when creating new Project

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#392]
After pulling https://github.com/DDMAL/Rodan/commit/a0e87f2ef2ad2428d32bf493cb10dfbee177b0bc I'm continually getting 500s when POSTing a new Project. Rodan is logging the following error:

`
local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/mrbannon/virtual_environments/rodan-vis/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/mrbannon/virtual_environments/rodan-vis/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/mrbannon/virtual_environments/rodan-vis/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: function publish_message(text) does not exist
LINE 1: SELECT publish_message(notify)
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT publish_message(notify)
CONTEXT:  PL/pgSQL function object_notify() line 18 at PERFORM
`

It looks like the DB triggers are causing a problem somewhere. Should I be doing something to allow the triggers to work? (Note: after pull, did makemigrations and migrate.)

**Comment by lingxiaoyang** [comment]
https://github.com/DDMAL/Rodan/wiki/Set-up-Rodan-core#set-up-postgresql-database-trigger-for-websocket-messaging


This link should help. It's ugly for now as it must be done manually. The purpose is to create the Python function as PostgreSQL superuser, and grant its execution permission to a normal db user, because we don't want Rodan to use a superuser to contact the database.

**Comment by lingxiaoyang** [comment]
A normal db user can create functions in PSQL language, but PostgreSQL considers Python functions as insecure and doesn't allow a normal user to create Python function.

**Comment by lingxiaoyang** [comment]
Perhaps, still, we need a better way of creating this function as superuser when Rodan is installed step-by-step. The automatic deployment script takes care of it.

**Comment by lingxiaoyang** [comment]
@mrbannon  solved on your testing server. The function `publish_message` was created in `postgres` database but not `rodan` database. I logged to `rodan` database as superuser by:

    sudo -u postgres psql rodan

Then created language `plpython` and function `publish_message` there. Then it worked.
