### ISSUE TITLE
Script for creating trigger function in PostgreSQL as superuser.

### ISSUE THREAD

**Issue by lingxiaoyang** [DDMAL/Rodan#393]
The trigger function needs to be written in Python, but concerning safety, PostgreSQL forbids a normal db user to create a Python function. What we're doing now is to create this function as PostgreSQL superuser, and grant its execution permission to the normal db user. However, this step requires the user to perform manually and easily leads to pitfalls (like in #392 , the Python function was created in database `postgres` instead of `rodan`). It's desired to have this step automated in a script (perhaps prompting user to log in postgres as a superuser and piping SQL statements into it somehow), to ease manual Rodan setup.

**Comment by mrbannon** [comment]
Thanks for taking care of this!
