### ISSUE TITLE
Workers should check server's version when starting.

### ISSUE THREAD

**Issue by lingxiaoyang** [DDMAL/Rodan#395]

**Comment by lingxiaoyang** [comment]
This needs a change in Job registration: now Rodan is automatically discovering jobs through module-level codes, and thus can only provide the version of a job package after loading it (and checking with the db). Whether database inconsistency or version conflict happen, the user is confused as the user cannot know which situation has happened. We'll need to move the job loading parts elsewhere instead of top module (`__init__.py`) of a job package, in order to make version checking meaningful to the user. 

Perhaps implement in the future. Removing from RELEASE 1.0.0

**Comment by kemalkongar** [comment]
Not relevant to the current setup of rodan or rodan-staging.
