### ISSUE TITLE
Query filtering based on creator

### ISSUE THREAD

**Issue by lingxiaoyang** [DDMAL/Rodan#396]
@ahankinson   We have objects with a `creator` field. How should it work with querying? 

I'm thinking if we can add users to a project, and then these users have permission to view (maybe modify/delete) everything in the project. Then `creator` field is only informative.

**Comment by lingxiaoyang** [comment]
@mrbannon   Maybe we also need to discuss this issue on Friday.

**Comment by mrbannon** [comment]
Tx!
