### ISSUE TITLE
'valid' flag on Workflow filtering isn't being respected

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#407]
Tried using valid__exact=true (and variations of "true"), but all Workflows were returned, regardless.

**Comment by ahankinson** [comment]
`valid=True` should work, no? It's a Boolean field.

**Comment by mrbannon** [comment]
I was using the Django query structure documented in the wiki:

https://github.com/DDMAL/Rodan/wiki/List-API

I DID try valid=true, but does it need to be 'True'? Regardless, the server
is down at the moment...waiting for Ling-Xiao.

On Tue, Jan 26, 2016 at 12:59 PM, Andrew Hankinson <notifications@github.com

**Comment by ahankinson** [comment]
Are you in Python? True is `True`

**Comment by mrbannon** [comment]
Truely? :)

**Comment by lingxiaoyang** [comment]
The GET parameter in URL may goes to a Python string in the backend. It's because I didn't test boolean fields...

This will also go to the master branch first.

**Comment by lingxiaoyang** [comment]
Well, this works:
`http://localhost:8000/workflows/?valid=True`

But this doesn't:
`http://localhost:8000/workflows/?valid__exact=True`

**Comment by lingxiaoyang** [comment]
@mrbannon   I find all `field__exact` are not working, including other non-boolean fields like "uuid", "name", ...

So don't use `field__exact=xxx`, use `field=xxx`.
