### ISSUE TITLE
Improve Job migration

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#408]
Job migration often fails, either during migration or after when accessing the server. As this problem persists I will post cases and the associated errors.

**Comment by lingxiaoyang** [comment]
1. Handle the situation when there are workflowjobs using the job to be updated.

2. Don't suppress any problems (like ImportError) during job migration. 

This fix will go to master branch first.

**Comment by mrbannon** [comment]
Thanks!
