### ISSUE TITLE
Get Resources for InputPort

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#411]
If I have an InputPort that can takes different resource types, I'd like to query the server to return those resources that are of those resource types.

Two options here:

- have a query against Resources that allows IN
- custom query for returning those resources that satisfy an input port

The first is probably the best, but whatever you want to do is fine by me. Tx.

**Comment by lingxiaoyang** [comment]
Use this:

`http://localhost:9000/resources/?resource_type__in=89c57edd-d4b3-42d6-88e7-8cb0d6330c77,bb384bc6-bafd-42a6-ad2e-e8db5be8da14`
