### ISSUE TITLE
ResourceType management

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#412]
Suppose job package A defines a ResourceType "png". Job package B ALSO defines a ResourceType "png". From what I can tell, Rodan sees these as two distinct ResourceTypes. This can cause confusion.

- Do we want Rodan to only allow one ResourceType per mimetype?

- If not, it then becomes the responsibility of the person maintaining a job package to make sure their ResourceTypes aren't "duplicates" of existing ResourceTypes. However, in this case we need to have more control over ResourceType management on the admin side. That is, the Rodan admin should be able to remove ResourceTypes with ease (just in case duplicates were created).

- Should the migration of job packages be "intelligent" in the sense that it will detect duplicates before putting them into the database?

- Is there a way to clear the database of known Jobs and ResourceTypes?

**Comment by lingxiaoyang** [comment]
1-3. This might be a bug. Let me check the code.

-----

4. What are "known" Jobs and ResourceTypes? @mrbannon

**Comment by mrbannon** [comment]
By known Jobs and ResourceTypes I just mean whatever exists in the database. I suppose this just applies to ResourceTypes iff Rodan is not able to get rid of duplicates.

**Comment by lingxiaoyang** [comment]
@mrbannon   It's weird. Rodan does have the "unique" restriction on mimetypes:

See https://github.com/DDMAL/Rodan/blob/master/rodan/models/resourcetype.py  L40:

    mimetype = models.CharField(max_length=50, unique=True, db_index=True)

And lines 47-53 define a `load` function that deals with duplicate mimetypes when loading them.

Can I see your definition of the two resource types?

**Comment by mrbannon** [comment]
Actually, this might be my misunderstanding. Let me get back to you. Sorry
about the confusion...

**Comment by mrbannon** [comment]
After our discussion:

- when migrating, it would be great if the script could identify duplicate ResourceTypes during migration and give an option either to (1) ignore the new one or (2) use the new one; all this really does is edit the description

- need a way to wipe the database of ResourceTypes
