### ISSUE TITLE
exact filtering not working

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#414]
exact__category on the Jobs list doesn't seem to work...

http://132.206.14.136/jobs/?category__exact=Indexer

Note that I'm getting non-Indexer Jobs.

**Comment by lingxiaoyang** [comment]
Don't use exact... It's not working sometimes for an unknown reason (I think a bug in django-filter).

Just use category=indexer

When do you need to exclude a certain category of jobs?

Le 19 f?vr. 2016 ? 11:29, Ryan Bannon <notifications@github.com<mailto:notifications@github.com>> a ?crit :


exact__category on the Jobs list doesn't seem to work...

http://132.206.14.136/jobs/?category__exact=Indexer

Note that I'm getting non-Indexer Jobs.

-

**Comment by lingxiaoyang** [comment]
In other words, whenever the client sees "exact", it should be translated to 'field=value' in GET query.

Le 19 f?vr. 2016 ? 11:29, Ryan Bannon <notifications@github.com<mailto:notifications@github.com>> a ?crit :


exact__category on the Jobs list doesn't seem to work...

http://132.206.14.136/jobs/?category__exact=Indexer

Note that I'm getting non-Indexer Jobs.

-

**Comment by mrbannon** [comment]
K, tx

This comes up when looking at a list of Jobs. I have a drop down that will
filter based on category to make it easier for the user to select jobs.

**Comment by mrbannon** [comment]
OK. I don't think I'll ever really use exact EXCEPT for enumerations. That
is, if I (the client developer) feel that a particular field is worth
enumerating (e.g. Job.category) I build an enumeration list that will get
realized as a drop down box.

**Comment by lingxiaoyang** [comment]
Do you need "not equal" as a lookup type at other places?

Le 19 f?vr. 2016 ? 11:36, Ryan Bannon <notifications@github.com<mailto:notifications@github.com>> a ?crit :

K, tx

This comes up when looking at a list of Jobs. I have a drop down that will
filter based on category to make it easier for the user to select jobs.

On Fri, Feb 19, 2016 at 11:33 AM, Ling-Xiao Yang <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Don't use exact... It's not working sometimes for an unknown reason (I
> think a bug in django-filter).
>
> Just use category=indexer
>
> When do you need to exclude a certain category of jobs?
>
> Le 19 f?vr. 2016 ? 11:29, Ryan Bannon <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>>> a ?crit :
>
>
> exact__category on the Jobs list doesn't seem to work...
>
> http://132.206.14.136/jobs/?category__exact=Indexer
>
> Note that I'm getting non-Indexer Jobs.
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/DDMAL/Rodan/issues/414>.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/DDMAL/Rodan/issues/414#issuecomment-186289895>.
>

-

**Comment by mrbannon** [comment]
Not at the moment, no. Can't imagine where I would need it...

**Comment by lingxiaoyang** [comment]
Ah, but you can't know all the options of an implied enumeration (the category is a string field), cam you?

Le 19 f?vr. 2016 ? 11:37, Ryan Bannon <notifications@github.com<mailto:notifications@github.com>> a ?crit :

OK. I don't think I'll ever really use exact EXCEPT for enumerations. That
is, if I (the client developer) feel that a particular field is worth
enumerating (e.g. Job.category) I build an enumeration list that will get
realized as a drop down box.

On Fri, Feb 19, 2016 at 11:35 AM, Ling-Xiao Yang <notifications@github.com<mailto:notifications@github.com>>
wrote:

> In other words, whenever the client sees "exact", it should be translated
> to 'field=value' in GET query.
>
>
> Le 19 f?vr. 2016 ? 11:29, Ryan Bannon <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>>> a ?crit :
>
>
> exact__category on the Jobs list doesn't seem to work...
>
> http://132.206.14.136/jobs/?category__exact=Indexer
>
> Note that I'm getting non-Indexer Jobs.
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/DDMAL/Rodan/issues/414>.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/DDMAL/Rodan/issues/414#issuecomment-186290650>.
>

-

**Comment by mrbannon** [comment]
Yes, I can, since I only use enumeration (for now) on collections where I
disable pagination. Put another way, I use enumeration on fields that I
know will have a small number of unique values and on lists that are static.

For example, for the Job list, I tell the client that the "category" field
should be marked for enumeration. When I get the Job list from the server I
make sure to get all the unique "category" values.

**Comment by lingxiaoyang** [comment]
OK

Le 19 f?vr. 2016 ? 11:45, Ryan Bannon <notifications@github.com<mailto:notifications@github.com>> a ?crit :

Yes, I can, since I only use enumeration (for now) on collections where I
disable pagination. Put another way, I use enumeration on fields that I
know will have a small number of unique values and on lists that are static.

For example, for the Job list, I tell the client that the "category" field
should be marked for enumeration. When I get the Job list from the server I
make sure to get all the unique "category" values.


On Fri, Feb 19, 2016 at 11:40 AM, Ling-Xiao Yang <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Ah, but you can't know all the options of an implied enumeration (the
> category is a string field), cam you?
>
> Le 19 f?vr. 2016 ? 11:37, Ryan Bannon <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>>> a ?crit :
>
> OK. I don't think I'll ever really use exact EXCEPT for enumerations. That
> is, if I (the client developer) feel that a particular field is worth
> enumerating (e.g. Job.category) I build an enumeration list that will get
> realized as a drop down box.
>
> On Fri, Feb 19, 2016 at 11:35 AM, Ling-Xiao Yang <notifications@github.com<mailto:notifications@github.com>
> <mailto:notifications@github.com>>
> wrote:
>
> > In other words, whenever the client sees "exact", it should be translated
> > to 'field=value' in GET query.
> >
> >
> > Le 19 f?vr. 2016 ? 11:29, Ryan Bannon <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>><mailto:
> > notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>>> a ?crit :
> >
> >
> > exact__category on the Jobs list doesn't seem to work...
> >
> > http://132.206.14.136/jobs/?category__exact=Indexer
> >
> > Note that I'm getting non-Indexer Jobs.
> >
> > -
> > Reply to this email directly or view it on GitHub<
> > https://github.com/DDMAL/Rodan/issues/414>.
> >
> > -
> > Reply to this email directly or view it on GitHub
> > <https://github.com/DDMAL/Rodan/issues/414#issuecomment-186290650>.
> >
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/DDMAL/Rodan/issues/414#issuecomment-186291487>.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/DDMAL/Rodan/issues/414#issuecomment-186293203>.
>

-
