### ISSUE TITLE
'name' field to ResourceTypes

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#415]
It would be very helpful if ResourceType had a (nullable) 'name' field. Right now the only opportunity to have any kind of human-readable info associated with a ResourceType is the 'description' field.

Given our earlier discussion about ResourceType management, this field could be overwritten (or not) during migration (at the discretion of the one maintaining the Rodan server).

**Comment by lingxiaoyang** [comment]
I don't think a 'name' field makes sense as MIME-types are already names. I think what you propose is a unified 'description' field (sometimes given by the server administrator if its descriptions are different across job packages). We can add a 'full_description' field if we need, storing the descriptions from all job packages. For example: 

Package A defines "image/png" as "PNG image", and Package B defines it as "Image in PNG format". The administrator wrote "PNG type" as the final description. Then the object will have:

````
"description": "PNG type"
"full_description": "PNG image (Package A)\nImage in PNG format(Package B)"
````

How about this?

**Comment by mrbannon** [comment]
Just keep it the way it is.
