### ISSUE TITLE
New fields and GET parameters for ResourceLists

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#417]
At the moment Resources have a very useful field 'origin' that maps to the Output from which it was generated (or null if it is a user-uploaded Resource). Also, the Resource API has 'result_of_workflow_run'; this lets the client easily retrieve all Resources associated with a WorkflowRun.

I think the new ResourceList model should also have 'origin' as well as the API letting the client get ResourceLists associated with the WorkflowRun.

**Comment by lingxiaoyang** [comment]
It has origin in database... I just forgot to include it in its serializer.
