### ISSUE TITLE
Workflow becomes invalid after using it in import

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#419]
Here's the scenario:

- Workflow A is valid
- I create new, empty Workflow B
- I import Workflow A into Workflow B (i.e. create a WorkflowJobGroup from Workflow A and add it to Workflow B)
- I validate Workflow B

Workflow A is now invalid. It shouldn't be.

**Comment by lingxiaoyang** [comment]
Note: the quick fix has performance impacts. But you can develop on it right now.

**Comment by mrbannon** [comment]
k, tx
