### ISSUE TITLE
Resource 'uploaded' query param should recognize True or False

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#425]
Right now, 'uploaded' doesn't recognize its value when being used as a filter. See:

https://github.com/DDMAL/Rodan/blob/master/rodan/views/resource.py#L74

It should take into consideration whether it has a value. If it does, it should use that value (True or False).

**Comment by Nicky666** [comment]
Fixed on commit 26f937a65268aa09812d579ed232a9980b6fa9c7

**Comment by ahankinson** [comment]
👍 🎉
