### ISSUE TITLE
Launching job from within another job

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/Rodan#426]
It would be really cool if a job could launch another job programmatically.

For example, the Interactive Classifier job could launch a regular Classifier job to do its classification portion.

This technique would allow for more code-reuse than the current implementation.

**Comment by lingxiaoyang** [comment]
Yes it is possible but not very obviously. You can write the code like:

````
from celery import registry

# in run_my_task() method:
# first prepare the parameters
try:
    registry.tasks['package.job_name'].run_my_task(inputs, settings, outputs)
except Exception:
    # handle exception
# then check the output file
````

**Comment by AFFogarty** [comment]
Ok, I will try this.

**Comment by mrbannon** [comment]
Why do you want to do this? Code reuse shouldn't be as much of a concern as
workflow reuse.

**Comment by mrbannon** [comment]
I'm going to close this as it really shouldn't be done. This should be facilitated as a sub-workflow.
