### ISSUE TITLE
Implement secure websockets

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#428]
Right now the websockets are not secure (ws). We need to use secure websockets (wss) if we want to use sockets AND HTTPS (assome browsers don't let you mix these).

Redis should have support for wss, but Rodan doesn't use it at the moment. We'll need Rodan to suport this.

**Comment by Nicky666** [comment]
depends on #430

**Comment by mrbannon** [comment]
AWESOME!!! wss is running on prod!!!
