### ISSUE TITLE
Include uuid of owning project in web socket messages

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#430]
Right now the web socket messages give the UUID of the model that was updated/added/deleted. In some instances, the client needs to know the root project that contains the model.

For example, suppose user A is looking at the list of workflows in their project. If user B adds a workflow but in a DIFFERENT project, user A's client has no way of knowing if an update to the workflow list is warranted since the owning project is unknown.

Right now, anytime there is a socket message, the client updates those models in the current view. This is fine with very little activity on the server. But with lots of activity, the client should only be updating when it is absolutely necessary (i.e. when a model has been updated in the currently loaded project).

**Comment by Nicky666** [comment]
I was not able to install plpython2 on mac which is needed for post-update trigger in postgres database

**Comment by ahankinson** [comment]
Why not?

**Comment by Nicky666** [comment]
I cannot use brew or pip. The solutions online include using python 3 or apt-get.

**Comment by ahankinson** [comment]
Build postgres with Python support. So

1. Check how to do it:

```
$> brew info postgres
...
--with-python
```

2. Reinstall postgres and use the `--with-python` flag (you may need to uninstall postgres first):

`$> brew install postgres --with-python`

3. Create the PL/Python extension in postgres: `CREATE EXTENSION plpythonu`

4. Complain again if that doesn't work. :)
