### ISSUE TITLE
Naming results

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/Rodan#431]
Right now (at least in the Rodan client) it seems that everything is named "Output of workflow blah." It would be nice if this could be named after the job name that created it, so "output of job Sauvola" or "output of job Miyao". That would help to distinguish the results.

I'm not sure if this belongs in Rodan or Rodan Client, so I'm putting it here but feel free to move it if necessary.

**Comment by mrbannon** [comment]
I think this would be a reasonable naming convention:

<ORIGINAL RESOURCE NAME> - <JOB NAME>.<EXT>

Putting in the Workflow name or the Workflow Run name isn't useful as those names may change.

**Comment by Nicky666** [comment]
The extension of the file would make the name too long and it is also redundant since the type of file is shown; so I talked to Andrew and decided to remove it. please let me know if you think it is necessary.

**Comment by mrbannon** [comment]
OK, sorry about the change:

```
<JOB NAME>
```
In the description, it would be great to populate it with the following:

- Workflow name (and URI)
- WorkflowRun name (and URI)
- Job name (and URI)
- WorkflowJob name (and URI)
- WorkflowJob settings (available from the associated RunJob)
- RunJob name (and URI)
