### ISSUE TITLE
Define DIVA jpeg2000 conversion job

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#432]
Right now the jpeg2000 conversion job for DIVA is hard-coded as 'rodan.jobs.conversion.to_jpeg2000'. If we're going to use a job package to do jpeg2000 conversion it should be a setting in settings.py.

Please do the following:

- add setting DIVA_JPEG2000_CONVERTER (make sure to also put this in in the necessary configuration scripts)
- uses this setting in 'create_diva' method

**Comment by Nicky666** [comment]
Fixed in commit ec133d942c5bd59a0822f3b6c150fc09b65fb2a1
