### ISSUE TITLE
WorkflowRun delete Resources option

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#434]
Please add a flag to the WorkflowRun DELETE call. If true, delete resources generated by the WorkflowRun (default is false).

**Comment by Nicky666** [comment]
In REST Framework, you cannot send a query parameter on DELETE (due to many reasons including the fact that it would violate the uniform interface)
So we either have to delete all resources with the workflowrun or not. 
Another approach would be to delete the resources using a new method not the delete workflowrun. This method would be called with the delete workflowrun method.

**Comment by mrbannon** [comment]
I say create a new rest call that deletes the workflow run and resources.
We might have to rename some calls

**Comment by ahankinson** [comment]
http://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-19#section-6.7

I think the question is a server-side one, though. What are the use cases for saving the Resources independent of the WorkflowRun? What are the use cases for deleting them?

**Comment by Nicky666** [comment]
And by the way, after I implemented the delete feature for workflowruns a few weeks ago, resources who are generated by a deleted workflowrun can be deleted. (if workflowrun associated to a resource is not deleted, the resource cannot be deleted.)

**Comment by mrbannon** [comment]
Case for deleting them:
- once the WorkflowRun is deleted they lose their origin; that is, the
action that indirectly created them no longer exists, so they lose context
relative to a Workflow

Case for keeping them:
- they're still Resources that might have value to somebody down the line
(if the user knows they exist)

I'm thinking it might be best just to delete them without question.

**Comment by mrbannon** [comment]
Delete the Resources :)

**Comment by mrbannon** [comment]
Change of plan - don't do it. too complicated for the moment.
