### ISSUE TITLE
Create many-to-many relation between Resource and ResourceList

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#444]
Right now, Resources are associated with ResourceLists by saving the url of the Resource in a ResourceList. What would be better is to create a many-to-many relationship between Resource and ResourceList.

How you would want to do this is up to you (probably best to define the many-to-many field 'resource_lists' in Resource).

The Resources must still all have the same ResourceType.

**Comment by mrbannon** [comment]
The ultimate goal is to query Resources by ResourceList. Since there could be a large number of Resources associated with a ResourceList it's best to treat the returned Resources as paginated results.

**Comment by mrbannon** [comment]
Sorry...should probably be 'resourcelists', not 'resource_lists'.

**Comment by mrbannon** [comment]
Also, we need to make sure that a Resource CAN'T have its ResourceType changed if it belongs to a ResourceList.

**Comment by ahankinson** [comment]
I would think that the field should be on ResourceList: `resource_list.resources` makes more sense than `resource.resource_lists`. 

If you want the reverse relationship, you can also do:

```python

class ResourceList(model.Models):
    ...
    resources = model.ManyToManyField("rodan.Resource", related_name="resource_lists")
```

Which would give access to `Resource.resource_lists`.

I think the results would need to be paginated at a special view level, so 

`http://example.com/resourcelists/123/resources` 

(or something like this) would return a paginated list of resources for that resource_list, but it would not be a good idea to return paginated results inside of a serialized `resourcelist` object.

**Comment by mrbannon** [comment]
I suggested the other way as it was analogous to the example given by the
Django documentation:

https://docs.djangoproject.com/en/1.9/topics/db/examples/many_to_many/

Also, I don't see why results can't be paginated straight from the
resources view:

http://example.com/resources/?resource_list=someresourcelist

This would be more consistent with the way we get other lists for other
models.

On Mon, Jun 13, 2016 at 12:25 PM, Andrew Hankinson <notifications@github.com

**Comment by ahankinson** [comment]
It's the ResourceList that 'contains' the Resources, so it makes sense to put the container attribute on the list, and not on the item that's in the list, no?

> Also, I don't see why results can't be paginated straight from the resources view:
> `http://example.com/resources/?resource_list=someresourcelist`

That's awkward. Do you have to provide the full URI for `someresourcelist`?

**Comment by mrbannon** [comment]
"someresourcelist" would be a UUID. So, nothing awkward about it - it would
be the exact same way we get other lists with a container as a filter.

As for ResourceLists containing the Resources, I agree that it makes sense
to put the container attribute on the list. But, again, I was going by the
example provided by the Django documentation.

https://docs.djangoproject.com/en/1.9/topics/db/examples/many_to_many/

On Mon, Jun 13, 2016 at 10:47 PM, Andrew Hankinson <notifications@github.com

**Comment by Nicky666** [comment]
There already is a many-to-many relation between resource and resourcelist. I implemented the rest of it.
