### ISSUE TITLE
Incoming POST request listener

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/Rodan#449]
To support both the ELVIS database and the Musiclibs database, we should add the ability to listen for POST requests to run a particular workflow.

Here's the use case: A new source is indexed in Musiclibs. The Musiclibs site fires a POST request to `https://rodan.simssa.ca/incoming/` with some information (TBD). Rodan uses said information to automatically configure and run a pre-built OMR workflow. The output of this workflow is then fed back into Musiclibs (somehow).

The "information" would likely need to be configurable, but it should probably at the minimum include a) the name or URI of the workflow to run, b) a list of the initial resources, c) a secret validation token.

This would work the same for ELVIS database, and can be the mechanism through which we can automatically index and then re-upload VIS or jSymbolic results to the ELVIS database.

See DDMAL/musiclibs#98

**Comment by mrbannon** [comment]
This is not needed since it simply requires two REST calls:

- upload resource
- create workflowrun
