### ISSUE TITLE
Get authtoken from viewer URL

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#453]
Assume we have the following viewer URL for a Resource:

https://rodan.simssa.ca/resource/uuid/viewer/

When opening in a new tab we cannot set the auth token in the header (javascript doesn't allow this). What we CAN do is add the auth token as a GET parameter. Imagine the URL sent to Rodan now looks like the following:

https://rodan.simssa.ca/resource/uuid/viewer/?authtoken=<some token>

Please do the following: when serving viewer URL requests in Rodan, if the auth token is not in the header, check if 'authtoken' exists as a GET parameter and use that instead. Django currently return a 40x response if the token isn't in the header, so you may have to investigate how to circumvent that behaviour.

**Comment by lingxiaoyang** [comment]
Ryan, I don't think it's good to write the authtoken in the URL as the location object is global and the token can be read by any other scripts. I encountered this problem with interactive jobs and I added a temporary access code there. I suggest using the same method: 1. Before visiting the viewer url, do another GET request to obtain a temporary access code; 2. Then put this code in URL of the resource viewer.

On Jul 26, 2016, at 12:22 PM, Ryan Bannon <notifications@github.com<mailto:notifications@github.com>> wrote:


Assume we have the following viewer URL for a Resource:

https://rodan.simssa.ca/resource/uuid/viewer/

When opening in a new tab we cannot set the auth token in the header (javascript doesn't allow this). What we CAN do is add the auth token as a GET parameter. Imagine the URL sent to Rodan now looks like the following:

https://rodan.simssa.ca/resource/uuid/viewer/?authtoken=

Please do the following: when serving viewer URL requests in Rodan, if the auth token is not in the header, check if 'authtoken' exists as a GET parameter and use that instead. Django currently return a 40x response if the token isn't in the header, so you may have to investigate how to circumvent that behaviour.

-

**Comment by mrbannon** [comment]
Excellent idea

**Comment by ahankinson** [comment]
Note that constantly changing access keys caused all kinds of problems with @AFFogarty interactive classifier.

**Comment by mrbannon** [comment]
That was a different issue since he had to keep renewing his token so he
could submit his work. We only need to get the data once if im not mistaken.

**Comment by Nicky666** [comment]
Done on Viewer branch. Commit: a7735c15a0d7e2c5a89bd6aac965a190f81cb3d5
