### ISSUE TITLE
REST endpoint for user to manage permissions of Projects

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#454]
Right now the only way to change who can view/use a Project is through the Django admin. We need to allow the owner of a project to manage who can use a Project.

Please create a Django endpoint so a user can manage permissions of their own project. 

Let's assume user 'joe' creates Project A, and the UUID of the of Project A is 12345. When a user creates a Project, three things currently happen:

- a 'group' is created called 'project/12345/admin'
- a 'group' is created called 'project/12345/worker'
- 'joe' is added to both these groups

The endpoint should allow 'joe' to add and remove users to the 'worker' group.

When you're ready to tackle this issue, we can talk about it.

**Comment by lingxiaoyang** [comment]
Do we have it already? Can you try joe POSTing a list of usernames to

  *   project/12345/worker

, such as ['userA', 'userB'], and see if it works?

On Jul 26, 2016, at 4:45 PM, Ryan Bannon <notifications@github.com<mailto:notifications@github.com>> wrote:


Right now the only way to change who can view/use a Project is through the Django admin. We need to allow the owner of a project to manage who can use a Project.

Please create a Django endpoint so a user can manage permissions of their own project.

Let's assume user 'joe' creates Project A, and the UUID of the of Project A is 12345. When a user creates a Project, three things currently happen:

  *   a 'group' is created called 'project/12345/admin'
  *   a 'group' is created called 'project/12345/worker'
  *   'joe' is added to both these groups

The endpoint should allow 'joe' to add and remove users to the 'worker' group.

When you're ready to tackle this issue, we can talk about it.

-

**Comment by mrbannon** [comment]
I'll give it a try tomorrow.

**Comment by ahankinson** [comment]
just a comment: 'worker' sounds a bit too close to Celery 'worker.' How about "members"?

**Comment by mrbannon** [comment]
You're right! Missed that. Tx.

In order not to break anything I'm going to keep it as admin and worker.
The client will see something different, of course.

**Comment by mrbannon** [comment]
works
