### ISSUE TITLE
Migration failure

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#457]
@Nicky666 please check https://github.com/DDMAL/Rodan/commit/489c66b215e874066cbcf52e61f569c04a368516. At this commit I am not able to do a migrate. It gives me the following error when running `python manage.py migrate`:

```
django.db.utils.ProgrammingError: relation "django_content_type" does not exist
LINE 1: ..."."app_label", "django_content_type"."model" FROM "django_co...
```

**Comment by ahankinson** [comment]
What was the problem? It's useful if you give a short explanation of how you fixed it.

**Comment by mrbannon** [comment]
I'll try (sorry...should have explained earlier).

We were trying to do a change to User view permissions during migration.
However, the permissions we were trying to apply (to the User model) depend
on guardian being installed. This means that the change to permissions must
be called on the post_migrate signal applying to the guardian install. The
function that was written was made to fire on pre_migrate. This would work
if a Django migrate call was happening on an instance that was already
installed, but not on a fresh installation. To make it work for a fresh
install, I switched it to fire on the post_migrate signal for guardian
(hence the 'if' statement checking if the sender's name is 'guardian').
