### ISSUE TITLE
Repeating jobs

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/Rodan#467]
Some jobs (without exposed parameters to the user) need to be repeated a number of times to achieve the desired results (e.g., Gamera's Dilate). Hence, it would be great to have the ability to iterate a specific job a number of times and only store the output of the last iteration.

**Comment by matangover** [comment]
Wouldn't it be better to just expose the desired parameters?

**Comment by vigliensoni** [comment]
Yes, but some Gamera jobs do not expose those parameters (e.g., Dilate)

**Comment by ahankinson** [comment]
I think it would be better to just chain the job n times. otherwise there will be logic in the job for doing the loop.

**Comment by vigliensoni** [comment]
Yeah, that is the workaround I am using, but I am getting n intermediate
results that I don't care about (and that are hard to keep track of)

**Comment by ahankinson** [comment]
I would avoid putting too much logic in the jobs themselves. You could also create your own job package that has iterating job functionality, but I wouldn't put iterating a job part of the core of Rodan.

**Comment by vigliensoni** [comment]
A package with iterating job functionality and the number of iterations
exposed to the user seems fine. As it is now, chaining jobs just clutter
the resources. close #467.
