### ISSUE TITLE
Other processes hang after first completes

### ISSUE THREAD

**Issue by EricHanLiu** [DDMAL/Rodan#469]
When running a workflow where a job has multiple resources in its input (and hence multiple jobs), once a first job finishes the rest of the jobs seem to halt yet retain their `processing` status in Rodan. No error messages are displayed in the terminal after the first process completes, and if running synchronously they should all complete around the same time.

The exact case was running Calvo's fast pixel-wise classifier with two score image resources in the image input port. After about 1h30, one of the two processes completed*. Over the next 15 hours, not a single message about workers was output to the screen and the second process never finished. When we checked up on it 15 hours later, it was still processing.
  **note: there were multiple worker messages while the processes were running, which indicated to us that the process was successfully running*

**Comment by deepio** [comment]
Was fixed.
