### ISSUE TITLE
Symbolic Links result in rodan timing out on start

### ISSUE THREAD

**Issue by noahbaxter** [DDMAL/Rodan#470]
When the jobs folder contains a symbolic link, created either through ln -s or right clicking a folder and creating an alias, the rodan_1 docker will time out or return an error during startup.

**Comment by vigliensoni** [comment]
This is not an issue of the Rodan repo. It should go in the rodan-docker
repo. https://github.com/DDMAL/rodan-docker

**Comment by noahbaxter** [comment]
my mistake, this bug has been moved
