### ISSUE TITLE
Job with no maximum number of input ports fails validation

### ISSUE THREAD

**Issue by JRegimbal** [DDMAL/Rodan#498]
According to [the wiki](https://github.com/DDMAL/Rodan/wiki/Write-a-Rodan-job-package#1-describe-a-rodan-job) setting the maximum number of input ports to 0 means that there is no upper limit on the number of input ports for that type. However doing this in practice results in a job that can never be included in a valid workflow. The workflow including it will always have the error `WFJ_TOO_MANY_IP` and fail validation since any number of input ports will exceed 0.

**Comment by malajvan** [comment]
Fixed with #950
