### ISSUE TITLE
Update psycopg2 version in requirements.txt

### ISSUE THREAD

**Issue by lingxiaoyang** [DDMAL/Rodan#504]
I experienced an issue during Django startup regarding the conflict between psycopg2=2.7.1 (on develop branch) and its dependency glibc 2.26. Need an update of psycopg2 to a version higher than 2.7.3.2.

Or better, use this in requirements.txt (also recommended for other packages):
````
psycopg2>=2.7,<2.7.99
````

Refs: https://github.com/psycopg/psycopg2-wheels/issues/2

Building on Ubuntu 18.04, Python 2.7, my error messages were:
1) `RuntimeError: populate() isn't reentrant` when `./manage.py shell`
2) `ImportError('/usr/local/lib/python2.7/site-packages/psycopg2/.libs/libresolv-2-c4c53def.5.so: symbol __res_maybe_init version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference',)` when looking into it with pdb.

**Comment by deepio** [comment]
Issue was fixed without closing, current version is `psycopg2==2.8.4`
