### ISSUE TITLE
OMR workflow - Summer 2020

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/Rodan#529]
- [ ] Maintain and have up and running production-ready and development versions of Rodan and OMR jobs 
- [ ] Triage and fix Rodan and jobs issues along all OMR workflow 
- [ ] Implement improvements to Rodan based on user feedback
- [ ] Implement Gamera's Biollante GA optimization as RODAN job. Double check that the features used by Biollante are normalized, so that they are size independent.

**Comment by kemalkongar** [comment]
Closed as the 2021 priorities have changed and are being updated internally.
