### ISSUE TITLE
Deleting a workflow run should show all jobs are cancelled.

### ISSUE THREAD

**Issue by deepio** [DDMAL/Rodan#556]
When trying to delete a workflow run, it does stop executing, but there is no information showing this. 

@martha-thomae ran an end2end OMR workflow with 220 resources (images + transcript text) and when she tried to delete it (in addition to never getting deleted) the individual jobs still show status = “processing,”. The actual jobs are cancelled, they are not processing and they are not in the queue either. The status = “processing” of these jobs is confusing to the user, who doesn’t know that the jobs are not in the queue anymore.

**Comment by malajvan** [comment]
Tested Running a simple workflow and deleting the Workflow Runs. This results in the associated individual jobs in Run Jobs also seeming to disappear.
