### ISSUE TITLE
Typo in websocket.ini

### ISSUE THREAD

**Issue by napulen** [DDMAL/Rodan#560]
https://github.com/DDMAL/Rodan/blob/c942943d2075b7276ca51c7e6714f5bb89be2887/websocket.ini#L10

"developpers" -> "developers". Two instances of this string.

**Comment by kemalkongar** [comment]
Pull request from kemal_dev should fix it. I dunno what the protocol is for working on this stuff on the weekend but if I see other minor issues I may just fix them (given it's ok to do so!).

**Comment by napulen** [comment]
Hey, no official policy regarding weekends. I think it's fine, worst case scenario, people will see it on a weekday.

Checking PR now
