### ISSUE TITLE
Rename/Remove .travis.yml while migrating to gh-actions

### ISSUE THREAD

**Issue by napulen** [DDMAL/Rodan#566]
I was too lazy to do it on my `napulen` branch, but as we keep trying out changes on the gh-actions yml file, we should change the name of the `.travis.yml` file so that Travis doesn't try to build. It'll just get us deeper and deeper in that "no credits left" hole.

Relevant to `napulen` and `gabbydev` branches.

**Comment by raviraina** [comment]
@napulen given our current setup with TravisCI, is this still an issue? They mentioned that we can request credits when needed (when/if we run out).

**Comment by napulen** [comment]
I don't think it is an issue anymore

**Comment by napulen** [comment]
If it is, feel free to reopen. I haven't been monitoring our TravisCI credits. We can do that one or two weeks from now and see that our usage looks healthy.
