### ISSUE TITLE
Feature Request: Hot key bindings

### ISSUE THREAD

**Issue by thesoundbyle** [DDMAL/Rodan#570]
- [ ] Delete hot key
- [ ] Scroll drag hot key

**Comment by JoyfulGen** [comment]
@PythonSemicolon I have no idea! Very mysterious.

There's already a hot key binding to delete glyphs from the training data and confirm that a suggested classification is correct, so the only other useful shortcut I can think of would be a zoom in/out shortcut for the Classifier Glyphs/Page Glyphs/Preview Image windows.

**Comment by PythonSemicolon** [comment]
As mentioned by @JoyfulGen, these hotkeys are no longer necessary. I will incorporate the zoom in/out functionality when resolving #571, but for now, this issue can be closed.
