### ISSUE TITLE
Request: A tool that centers the selected symbol

### ISSUE THREAD

**Issue by thesoundbyle** [DDMAL/Rodan#574]
Most of the time, when trying to classify symbols a lot of time is spent searching for the highlight. I would be nice if the symbol became centered on the page or there was a tool that helped find the symbol quicker. 

![221](https://user-images.githubusercontent.com/62864127/117499832-c6571000-af49-11eb-9398-c6d202d098ba.jpg)

**Comment by GabbyHalpin** [comment]
fixed on staging
