### ISSUE TITLE
IC Summer 2019 overview

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/Rodan#575]
- [ ] Display images with IIIF/DIVA
- [x] Create mapping tool between IC Gamera and MEI encoding. This interface should map made up names to MEI 4.0.
- [ ] Implement Gamera's Biollante optimization as RODAN job

**Comment by kemalkongar** [comment]
Due to changing priorities, bug fixes will be prioritized and feature requests will be discussed internally.
