### ISSUE TITLE
Resize selection box based on resizing class names

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/Rodan#579]
On Safari, when resizing the class names pane only changes the width of the class names. Should change the width of class names, editing box, and classifier and page glyphs, and preview image.

![screen shot 2018-08-13 at 10 20 15 am](https://user-images.githubusercontent.com/492229/44037502-7f1a52b2-9ee2-11e8-81f8-d543f121c44e.png)

**Comment by thesoundbyle** [comment]
issue no longer occurs. clsoing.
