### ISSUE TITLE
Right click on class name should display the class in classifier pane

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/Rodan#580]
By right clicking on a class name (e.g., for changing the name of a class) the classifier glyphs pane should display that class centred or highlighted.

As of now, the classifier does not display the class name.

![screen shot 2018-08-13 at 9 45 49 am](https://user-images.githubusercontent.com/492229/44035512-b148340c-9edd-11e8-8dae-c1020d40b83b.png)

**Comment by softcat477** [comment]
Already working
