### ISSUE TITLE
Manually classified glyphs don't always appear first in their rows

### ISSUE THREAD

**Issue by nminnie** [DDMAL/Rodan#584]
Green glyphs, which have been manually classified, should appear before the yellow glyphs in each row.
![screen shot 2018-08-08 at 2 48 11 pm](https://user-images.githubusercontent.com/26179067/43857733-349c2650-9b1a-11e8-9670-8cfacec7fcc4.png)

**Comment by thesoundbyle** [comment]
issue no longer occurs, closing.
