### ISSUE TITLE
IC browser window doesn't always render correctly when it is first opened

### ISSUE THREAD

**Issue by nminnie** [DDMAL/Rodan#591]
Sometimes when the Interactive Classifier browser window is opened, there is a blank gap between the classifier pane and the page glyphs pane.
If we click and move the mouse, the window then renders itself correctly.

![screen shot 2018-06-18 at 2 22 37 pm](https://user-images.githubusercontent.com/26179067/41620921-2b766328-73d9-11e8-9930-28515d64da2d.png)

**Comment by thesoundbyle** [comment]
Issue no longer occurs. Closing.
