### ISSUE TITLE
Get authentication token from Rodan

### ISSUE THREAD

**Issue by pf-physics** [DDMAL/Rodan#605]
Currently the interactive classifier uses ajax to get the authentication token from Rodan, but it doesn't pass the correct information. We might also rewrite this part of the script in Python or in bash.

**Comment by kemalkongar** [comment]
Closing the issue as the authentication method seems complete in the most recent version of Authenticator.js

**Comment by deepio** [comment]
Unfortunately it's not

**Comment by kemalkongar** [comment]
Does anyone have information on it? The issue discussion isn't exactly in-depth -- we'd work much faster if there was a prototyped design to fix it. If not, we'll add it to the pile of issues to look at once staging is completely up and running.

**Comment by deepio** [comment]
This is the hack around the problem, there was never any time to look into it further
https://github.com/DDMAL/rodan-docker/blob/aa7c238533367f699949bdcba59913f8812d3776/rodan/scripts/start#L38
