### ISSUE TITLE
Move Gamera-related job code into python3

### ISSUE THREAD

**Issue by martha-thomae** [DDMAL/Rodan#616]
In the future, we want to move the code of the interactive classifier into python3. This is the only job holding us to python2. The other gamera-related jobs involved in the OMR workflow can be implemented in other tools like scikit-learn: dilation, despeckle, and connected component analysis (CC analysis).

**Comment by sabrina0822** [comment]
@EMZEDI @malajvan have worked on updating to gamera-4 and moving IC to python 3. We have succesfully migrated all of the jobs excluding biollante and the miyao toolkit.
Unfortuantly since most of the gamera jobs are kind of woven together we can't update the IC until we move all gamera jobs to python 3 (i.e. the miyao toolkit is in the gamera-jobs folder so we need all jobs/toolkits within the folder to be in python 3 before we can push)

**Comment by EMZEDI** [comment]
UPDATE: Biollante module is also updated to python3. 
The commit ID is: 6fa0d2ceca185c7d654f26657a658c0885953429
And the changes are pushed to the migration_py3 branch. From now on we will create a branch for each update.

**Comment by malajvan** [comment]
Update: 
- Heuristic Pitch Finding is under debugging. 
- Miyao Staff Finder job moved to python3, all other toolkit jobs under gamera-rodan are left behind. Problems with building the dependency musicstaves toolkit were solved by eliminating irrelevant tasks with cpp files with deprecated PyClassObject instances and fixing the python2 wrappers. The musicstaves toolkit we're working on is currently [here](https://github.com/malajvan/musicstaves_rodan) (will be moved to DDMAL's github)
There is a problem when building and installing musicstaves on the container. It is documented through the container installation process below.

1.     clone https://github.com/malajvan/musicstaves_rodan and checkout the dev branch
2.    cd into repo and run `python3.7 setup.py build && python3.7 setup.py install`
3.    Important: after installation, you have to go into `/usr/local/lib/python3.7/dist-packages/gamera/toolkits/musicstaves/plugins/staff_finding_miyao.py` and change line 21 to `from . import _staff_finding_miyao` and go into `/usr/local/lib/python3.7/dist-packages/gamera/toolkits/musicstaves/plugins/musicstaves_plugins.py` and change line 26 into `from . import _musicstaves_plugins`

normally you would fix the issue before building and installing, but for some reason it won’t let me use `from . import <module>` in the repo and only allows it when we’re in the dist-packages. error
![image](https://user-images.githubusercontent.com/64571718/172882661-39810d7c-592c-49fc-9804-0deef2004bb5.png)
:

if i leave those line alone without the `from .` part, python can’t find the files at all. The files to be imported are different in the repo and the dist-packages. the ones in the repo are c++ files, while the ones in dist-packages are built files with extension .so

Will fix this also before the big PR.

**Comment by malajvan** [comment]
Update: Issue fixed with a try/except clause in the files pre-build and install.

**Comment by EMZEDI** [comment]
UPDATE: HPF fixed and the changes will be pushed soon!

**Comment by EMZEDI** [comment]
MEI_resizing job's output does not start with an `<?xml version="1.0" encoding="UTF-8"?>`. @sabrina0822 check that please. Thanks!

**Comment by EMZEDI** [comment]
✨ Issue solved and merged to gamera-rodan repository. More details can be found inside the following link:
https://github.com/hsnr-gamera/gamera-4/issues/49
