### ISSUE TITLE
vis_rodan job not working properly

### ISSUE THREAD

**Issue by napulen** [DDMAL/Rodan#624]
@slhowes reported that the `vis_rodan` job is not working properly in Rodan2

The description of the issue that @slhowes communicated via email:

> noterest is an indexer in the vis-framework, which is the only thing I use in Rodan. I set up a workflow called "noterest" that comprises a single job: the noterest indexer. The input for that indexer is pieces or movements in musicXML format. Before I feed the movements to the indexer, I label them all as "musicXML" in the Resources list (this much seems to be working properly).

> The expected output is CSV files (one CSV file per musicXML file), but right now the workflow is not running properly. For a little while it's status is "processing" and then the status changes to "failed"

> Strangely, it looks like it still produces output files (CSV) but these files do not "exist" (their value for "File exists" is "false") and when I try to download one, nothing happens.

> From what I remember, this exact problem occurred about a year ago (on the original Rodan Client) and I think @vigliensoni  was able to get it working.

> I have three other workflows besides the one called `noterest`, some with more than one job in them. At the end, I get four CSV files per movement which are then processed using my own code in Python.

**Comment by timothydereuse** [comment]
We have decided to remove this from Rodan for now. It uses versions of numpy that are simply too old for us to feasibly continue supporting. Will re-open if and when we can re-add this.
