### ISSUE TITLE
[MEI Encoding] <clef>, <sb> and <custos> are sometimes inside syllables--this should not happen

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Rodan#634]
The `<custos>`, `<sb>` and `<clef>` lines in MEI should be their own little category, all following each other at the end of a staff and before the next one, like so:

<img width="860" alt="253r normal clef:custos:sb" src="https://user-images.githubusercontent.com/83373378/167456871-76d388fb-e2d4-4f82-b2e0-ef07d9135a80.png">

However, in the straight-outta-omr file they often appear inside a syllable, like so:

<img width="881" alt="253r sb:custos NO" src="https://user-images.githubusercontent.com/83373378/167456881-ae0055bf-b53b-4480-af2f-6d627a07cff2.png">

In itself, the issue is just a semantic one. @annamorphism, could you confirm that those three elements should never be inside a syllable? Also, the issue sometimes appears to fix itself: from what I can tell, when I move the staff before or after the `<sb>` inside a syllable, all three elements move out of the syllable and become their own category. I don't know why this sometimes works, and sometimes not. I also don't know why some `<custos>`, `<sb>` and `<clef>` elements are inside syllables, and some are not. To be continued.

**Comment by annamorphism** [comment]
@sabrina0822 @JoyfulGen so if I understand this solution correctly, this is going to end a syllable and start a new one every time there is a clef or custos in the MEI file, correct? If so, that should guarantee we don't get clefs inside syllables, and it gives a correct result, BUT it could mean having to do a lot of regrouping if the error rate on identifying clefs and custodes is high. 
e.g. for a big syllable that has (bunch of neumes)(mistakenly identified custos)(more neumes)(another wrong custos)(even more neumes) won't this give us (syllable: bunch of neumes)(mistakenly ID'd custos)(syllable: more neumes)(another wrong custos)(syllable:even more neumes)?  And then the user would have to get rid of the mistakes and regroup the syllables? 

Let me know if I'm understanding correctly.

**Comment by sabrina0822** [comment]
@annamorphism @JoyfulGen yes that’s pretty much it. 
However, from what I understand neon is able to make it so that splitting doesn’t require more human interaction because of the precedes and follows attributes (they should link the two split syllables). So ideally the two syllables are considered one. @yinanazhou is this a correct assumption? 
For the situation you described I believe the user would only have to correct the mistakingly ID’d custodes and add them to the syllable (since the two split syllable components would be considered the same syllable).

**Comment by yinanazhou** [comment]
> Talked about this more with @annamorphism and here's what we thought:
> 
> Clefs inside syllables are rare enough (I think we've found 3-4 instances for 100ish folios) that we think it would be most efficient to make it so that clefs are never automatically inserted into syllables. When they do actually need to be inside the syllable, the human can do it. We found two ways that this could be done:
> 
> 1. Adding a button that can allow the user to insert a clef into the nearest syllable, like we already can for divisios. Clefs affect pitch though, so we don't know if this would work. @yinanazhou, what do you think?
> 2. If 1. doesn't work, another option would be to add a toggling function across clefs. So if the user selects syllables on either side of a clef, the option appears to link them, just as it does for syllables that cross staves.
> 
> I'm going to put these options in [DDMAL/Neon#650](https://github.com/DDMAL/Neon/issues/650) as well.

Sorry for the late reply. I think the first solution is doable. I can add the button to insert a clef into nearest syllable, and also update the pitches.

**Comment by yinanazhou** [comment]
> 

I'm sorry that I have to say the two syllables are not considered as one, it's more like they are linked together.

**Comment by JoyfulGen** [comment]
I actually think this wouldn't be so bad for the correcter. In @sabrina0822's example, the syllables are all toggled with each other and thanks to the fix in https://github.com/DDMAL/Neon/issues/783, interacting with toggled syllables immediately untoggles them and makes them into distinct syllables, so we know this won't cause additional chaos. Also, in my experience toggled syllables are often wrong (sorry), so untoggling them won't cause too much grief. 
My only concern is that this will mean that if there's a custos inside a syllable within a staff, that'll create toggled syllables on a staff, which will remain even if we delete the custos. @annamorphism, do we care?
