### ISSUE TITLE
"Save" button to change resource name hangs forever (at least 10 minutes)

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Rodan#635]
If I sign in to rodan2 and immediately change a resource name without doing anything else, the "save" button works fine. However, if I've run a job or done any other action within rodan, the "save" function hangs for a very long time. Refreshing the page makes the "save" button work again, but it would be more efficient if the user didn't have to do that.

**Comment by softcat477** [comment]
## Steps to recreate this issue:
1. Use this workflow.
![Screen Shot 2022-12-05 at 11 54 18 PM](https://user-images.githubusercontent.com/25975988/205835992-41418223-d8a8-48fc-a55b-b8984a65b164.jpg)
2. Upload two resources, assign them to the `Labeler` job, add a new label, run the job.
3. Wait until the job is finished. Rename a resource and click save. Rodan hangs.
4. Refresh the page. Rename and click save again. Rodan works.

https://user-images.githubusercontent.com/25975988/205836597-372870d3-22ba-41e3-a0fd-3f92fee9e28e.mo
