### ISSUE TITLE
Inconsistent UI display (possible browser problem)

### ISSUE THREAD

**Issue by carrieeex** [DDMAL/Rodan#652]
When opening the Neon job in Rodan2, the image sometimes is not displayed on the entire left screen, like in the image below (Salzinnes folio 072r, nearly half of the left screen is blank, which makes the editing space smaller):
<img width="1122" alt="072r example Neon UI" src="https://user-images.githubusercontent.com/59303880/119649691-7e931c80-be55-11eb-8a73-512569d275bb.png">

Normally I would expect the screen like this (Salzinnes folio 082r):
<img width="1128" alt="082r example Neon UI" src="https://user-images.githubusercontent.com/59303880/119649841-b39f6f00-be55-11eb-93a5-e9ce4b315ef7.png">

**Comment by malajvan** [comment]
The latest Neon still suffers from problems regarding showing background images (see #954) but I don't see this happening on Chrome anymore.
