### ISSUE TITLE
Pixel.js in Rodan job crashes with large image

### ISSUE THREAD

**Issue by KhoiTienNguyen** [DDMAL/Rodan#660]
Adding a large input image (~30Mb+) into Pixel.js job on Rodan causes the pixel browser to crash. The job on Rodan still appears as processing and available for processing, but clicking on Open shows Server Error (500). An example image to test this with is Image - 040.png from the MS73 dataset.

**Comment by softcat477** [comment]
Resolved in #760 (dev branch) and #753 (master branch)
