### ISSUE TITLE
Makefile command to fetch logs from docker containers on staging

### ISSUE THREAD

**Issue by timothydereuse** [DDMAL/Rodan#668]
It would be good if we had a command in the makefile that could automatically fetch logs of celery workers from queues on staging (e.g. the file `/code/Rodan/rodan-celery-GPU.log` so that we do not have to continually find the container running the job, get a shell into it, and manually navigate there. The `docker service logs` command only shows logs for each service's entrypoint, which is not always helpful.

For example, running `make get_logs SERVICE=gpu-celery` would result in finding the most recent container launched by that service that is currently running and performing `tail -f` on the `.log` file in its `Rodan` directory.

**Comment by softcat477** [comment]
Resolved in #762
