### ISSUE TITLE
Resizing the window breaks Rodan workflow canvas

### ISSUE THREAD

**Issue by p42ul** [DDMAL/Rodan#669]
After resizing the window in this way, the canvas is distorted and doesn't respond to user input.

Before resizing:
![Screen Shot 2022-06-10 at 10 16 12 AM](https://user-images.githubusercontent.com/2514777/173085331-86f965b5-d0ec-4a99-b3c8-add56d215fe2.png)

After resizing:
![Screen Shot 2022-06-10 at 10 16 37 AM](https://user-images.githubusercontent.com/2514777/173085396-f47196e6-c4c1-4b82-9240-9cd66d6d1a67.png)

**Comment by EMZEDI** [comment]
Currently working on this issue:
Just as an update: The issue of the grids being shrunk only happens on an external monitor for me which means that it is a @media issue and needs to be solved.
The issue will be solved (hopefully soon)

**Comment by EMZEDI** [comment]
#748
