### ISSUE TITLE
Rodan containers on develop branch cannot be started when running locally

### ISSUE THREAD

**Issue by malajvan** [DDMAL/Rodan#679]
***Issues:***
currently cannot `/run/start` the `rodan-main`, `py2-celery` and `py3-celery` containers without errors and problems. One of the main problem is Pixel cannot be pulled and built correctly when running `make remote_jobs`. There are also pymei and django dependencies issues. I suspect the latter 2 problems stem in the discrepancy between the dockerhub containers or some other python2->python3 problems.

***Plan:***
I tested and documented a temporary fix for running Rodan locally below. This does not fix the Pixel issues. Since problems with the newest commit are all python2, I will focus on testing and fixing the new python3 containers/branch implementations. 

***Temporary Fix:***
 in the Rodan repository,
`git checkout a3d07955fb66f6ef3b9d19937a9c2064a965c507`
in `rodan-main/code/rodan/jobs/register_all_jobs.py` comment out lines that registers Pixel (80->87)
and in `rodan-main/code/rodan/settings.py` comment out Pixel wrapper in the job queue  (150)

**Comment by sabrina0822** [comment]
<img width="857" alt="image" src="https://user-images.githubusercontent.com/90227881/174809741-632889f4-e2fb-424e-834a-eb1ac4be705d.png">

**Comment by sabrina0822** [comment]
This was fixed by removing gamera-4 off of develop for now. The next step is to eliminate all traces of old gamera off the migration_py3 branch to ensure that this error will not occur.
Testing migration_py3 is a bit difficult docker-wise because we haven't been able to pull the images off dockerhub. I looked into it earlier today and will continue to look into it tomorrow once the other build issue has been solved (gpu build failing)

**Comment by malajvan** [comment]
Neon installation problem through `make remote_jobs` was fixed by installing Pixel first, and Neon build might fail after creating neon_wrapper and pixel_wrapper. After discussion with the Neumes team, this error might stem from Neon and neon_pixel version mismatch after the big Neon change last week. Right now, pulling and installing Rodan locally work again, with the possibility of Neon not working properly. This will be fixed hopefully after neon_wrapper repo is updated.
