### ISSUE TITLE
Builds failing in all branches due to GPU-celery container build 

### ISSUE THREAD

**Issue by sabrina0822** [DDMAL/Rodan#687]
Noticed that all builds are failing on dockerhub with the same traceback.
<img width="890" alt="image" src="https://user-images.githubusercontent.com/90227881/174941965-d499796f-2020-4e79-a95e-dd27c5369b96.png">
This is the particular error: ImportError: cannot import name 'ParamSpec' from 'typing_extensions'
This problem occurs after downloading django-guardian (from rodan-main/code/requirements.txt - which is installed in the install_rodan script), once it starts the setup.py process. 
Interestingly enough this same requirements.txt file is called in multiple other dockerfiles and only causes an issue in the gpu container. Not fully sure why this is happening yet, will investigate more tomorrow.

**Comment by sabrina0822** [comment]
Upon running it locally the same error happens: 
<img width="542" alt="image" src="https://user-images.githubusercontent.com/90227881/174945174-e9022cd4-c23f-41d6-ba73-03f7c1f88012.png">

Will look into this more tomorrow

**Comment by softcat477** [comment]
also the latest commit `00f3a9` on dev branch pass the `ci/docker-cloud` test. Even through bandaid fix is still working in progress, it just magically passed the test.

**Comment by sabrina0822** [comment]
Seems like the problem went away without any fixes. Might be a one off problem, we have the fix in a separate branch should the problem reoccur!
