### ISSUE TITLE
Rodan local testing efficiency

### ISSUE THREAD

**Issue by EMZEDI** [DDMAL/Rodan#696]
I noticed that the developers have to run the same docker related and deployment related commands every time they want to debug and run Rodan locally. Therefore, I realized that this process could be more efficient using docker hub builds or cloud servers and automated scripts to run those commands and deploy Rodan for the developer to test the changes. 
_I am currently working on a bash script to automate those commands and ways to run Rodan on cloud for local testings._

**Comment by timothydereuse** [comment]
Shahrad - just cleaning up issues. Did you finish a script for this? Can this issue be closed?
