### ISSUE TITLE
Audio cue for end of workflow

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Rodan#728]
Waiting for a workflow to finish processing can be pretty long (up to 20 minutes). It would be helpful to have a *ding* or some such thing to signal when the IC or Neon file is ready for input. It would allow the human freedom to look away from the computer and work on other tasks while waiting for the processing to be done.

**Comment by malajvan** [comment]
@jackyyzhang03 is working on implementing a feature where rodan would send you notification emails (when workflow runs are done, etc.) (#962) Would the sound cue still be needed? Thanks!

**Comment by JoyfulGen** [comment]
@malajvan that sounds great! Notifications sound much more useful than a sound cue, so I'll close this issue.
