### ISSUE TITLE
Better feedback from rodan-client when workflow is not valid

### ISSUE THREAD

**Issue by timothydereuse** [DDMAL/Rodan#730]
<img width="349" alt="Screen Shot 2022-07-25 at 10 34 31 AM" src="https://user-images.githubusercontent.com/28409383/180802793-cd38785c-a540-453e-9af7-f96db05ae924.png">

Currently when a workflow is not valid, the only feedback the user gets is this message in the top-right of the screen. This message should be expanded to tell the user exactly what about the workflow is invalid. (We have had bugs where workflows that _should_ be runnable are listed as invalid, so this would help with debugging that as well.)

**Comment by EMZEDI** [comment]
@timothydereuse do you know if thise bugs are issued somewhere or not?
I am currently working on this issue.
