### ISSUE TITLE
[rodan-main in py3] Certain resource types not identified when uploaded 

### ISSUE THREAD

**Issue by sabrina0822** [DDMAL/Rodan#734]
Due to some changes in the way files are opened from python 2 to 3, certain resource types haven't been properly identified when uploaded onto rodan. Instead they are assigned as 'application/octet-stream'.

This was first noticed with PNG image types. After going into the postgres to check the resource database I found this traceback under the specific uploaded resource (the PNG assigned a type of application/octet-stream).

```
File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 412, in trace_task
     R = retval = fun(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 704, in __protected_call__
     return self.run(*args, **kwargs)
File "code/Rodan/rodan/jobs/core.py", line 61, in run
     mimetype = fileparse(infile_path)
File "/code/Rodan/rodan/jobs/resource_identification.py", line 157, in fileparse
     return mimetype_translation[magic_mime](filename, text_description)
File "/code/Rodan/rodan/jobs/resource_identification.py", line 31, in define_png
     data = f.read()
File "/usr/lib/python3.7/codecs.py", line 322, in decode
     (result, consumed) = self._buffer_decode(data, self.errors, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

Upon further investigation I ran a test in the resource_identification file and found that these file types are not being uploaded properly.
<img width="370" alt="image" src="https://user-images.githubusercontent.com/90227881/181081197-0c672454-a19e-46e2-8381-42094ea24c42.png">

@malajvan and I are working on this, will continue to keep this updated

**Comment by malajvan** [comment]
Fixed by opening files with `io.open` and some minor `hex` function changes. Fixed with commit `9d61c8eed202be66f3c31512f92a358d39155dd2`
