### ISSUE TITLE
Simplify how Rodan and celery register jobs

### ISSUE THREAD

**Issue by timothydereuse** [DDMAL/Rodan#736]
Currently, for a job to be registered and runnable in rodan it must be have an entry in `rodan-main/code/rodan/settings.py`, so that Rodan can "see" it, and a different entry in `rodan-main/code/rodan/jobs/register_all_jobs.py`, so that celery can "see" it. It would be much easier if there was only one place where you had to put the name of a job to enable it.

Separately, but related enough that it is worth working on at the same time, registering a job with Rodan requires importing the job's wrapper file, which ends up triggering every `import` statement. This means that the `rodan-main` container must have installed in its python environment _every single python package used by every job._ This is not great. It would be better if we found a way to register a job in Rodan without needing to import it, so that the rodan-main container can remain clean.

**Comment by sabrina0822** [comment]
The long awaited update!
Currently working on simplifying through the use of a yaml file. As of right now I've created the file with all the jobs (dictionaries of dictionaries), working on first changing the settings.py file to use this format and then will work on the registerAllJobs.py file

**Comment by malajvan** [comment]
recently updated the register_all_jobs and fix minor issues in the yaml file. Seemed to work on Rodan locally, waiting for the final build to do a comprehensive test.
