### ISSUE TITLE
Staging is down after rodan-main migration to python3

### ISSUE THREAD

**Issue by malajvan** [DDMAL/Rodan#739]
@sabrina0822 created the branch `staging` and the dockerhub tag `staging` for this issue

After the migration of Rodan-main from python2 to python3, staging is down due to various issues. The weird part is this is not reproducible locally. When `make staging`, images are pulled and containers are created successfully. However, `Rodan-main` container repeatedly restarts, therefore dragging `nginx` and other celery containers with it. 
When running `docker service logs --details --follow rodan_rodan-main` for more insights, we discovered the following problems:

**1. `rodan-main /run/start` time out at `chmod -R a+rwx /var`**
The line was added because when running Rodan locally we ran into permission issues with `/var`. This however does not affect staging and thus was commented out because the line takes a long time to execute and causes rodan-main to exit on timeout. We'll look into changing the var files' mode permanently and commit the changes on github instead of running the chmod line everytime we start the containers.

**2. Django is looking for the wrong PostgreSQL language**
![image](https://user-images.githubusercontent.com/64571718/183038259-014b4181-cb76-4e26-985a-48d7a0e6c620.png)
The PostgreSQL language `plpython2u` was being looked for despite all instances of `plpython` in our code base being changed to the expected `plpython3`. `plpython2` comes with Python2, so this error comes up after rodna-main migration to python3. 
@kqct and @EMZEDI looked into the Postgres container and found this:
![image](https://user-images.githubusercontent.com/64571718/183039004-c5d0714b-4651-4a8b-b74d-5f2ef935c07f.png)
Where `plpython2` still exists under the `pg_pltemplate` table and is referenced by both `plpython2u` and `plpythonu`.
They proceeded to change the reference to `plpython3` but failed to make a difference
Also, notice here
![image](https://user-images.githubusercontent.com/64571718/183040507-0357df58-bd1b-4627-9837-1eed45d36287.png)
The `postgresql-plpython3-11` is the language for PostgreSQL version 11, while ours is running version 9.6. The Postgres container is also running python3.5 and rodan-main is running python3.7. We're unsure if these discrepancies will cause problems in the future, but it's worth noticing

**3. `base.py` updating jobs and creating jobs in a weird manner**
@sabrina0822 has been working with Django migration and `migration.py` for a long time and noticed that `base.py` is updating jobs in a weird way. Actually, the problem with Postgres above stemmed from Miyao Staff Finding being updated through base.py. After further inspection, she concluded that it might be beneficial to delete all migrations, use the fresh Postgres container then run the migration in the Rodan-main afterward.

**Comment by malajvan** [comment]
@sabrina0822 (correctly) suspected that the error was coming from not having plpython2 under postgres' container and fixed the issue by downloading plpython(2) along with plpython3 (under this [commit](https://github.com/DDMAL/Rodan/commit/d6ea22f45e3b78e1236f120cb04afac669d47d91))

**Comment by malajvan** [comment]
Staging is "up", but is not running properly. In particular, uploading resources remain as `application/octet-stream` instead of the appropriate resource type, and jobs don't appear in the `Run Jobs` tab. Further investigation shows that the `celery` container restarts repeatedly (similar to what happened to `rodan-main` earlier.
As mentioned in part 1 of the first comment, the `chmod` line for var was commented out. However, this caused celery (which uses the similar images to `rodan-main` container) to restart on this error:
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/64571718/183340828-c9448d40-f80c-4789-980c-8a80df390f7c.png">

**Comment by sabrina0822** [comment]
My guess is that the changes that we implemented to fix the var issue in the rodan main start script weren’t implemented in the start celery script.
As for plpython2, I figured we should maybe try to remove it now that we were able to get it to run once with it. I think that it was needed to be in the Postgres container previously just for the most recent backup data but I think now there’s a chance it won’t be necessary (since our stuff uses plpython3u).

**Comment by sabrina0822** [comment]
I’m not sure if we will be able to run it without plpython2 but I think it may be worth a try since having both versions on the container isn’t ideal.

**Comment by malajvan** [comment]
I'll try to remove plpython2 and implement the `chmod /var` non recursively in the `start-celery` scripts to similar to the `start` script

**Comment by malajvan** [comment]
Tested building postgres with ONLY plpython3-9.6 works! ([commit](https://github.com/DDMAL/Rodan/commit/d5afc53a5b7cdb042c25dfded6ca7369a5b9ddf2)) a bit confused but could be because we needed to specify which version of postgres plpython should be?
Thinking of testing this theory on production...

**Comment by timothydereuse** [comment]
> 

What would testing this theory on production involve, exactly? Can you outline it step-by-step?

**Comment by sabrina0822** [comment]
@malajvan i think plpython2 was needed for the first initial migration because of the fact that we are updating the jobs not creating new ones. So the old versions of the jobs needed plpython2 to be updated but now they don’t.

**Comment by EMZEDI** [comment]
For production, we need to migrate the old database to the new source code (plpython3/ plpython3u) which requires the installation of plpython2 initially. But as of the next builds, we can remove the dependency on python2.
Is this also what you think @sabrina0822 ?

**Comment by sabrina0822** [comment]
Yes!

**Comment by malajvan** [comment]
Since staging is up, I'll close this issue
