### ISSUE TITLE
MEI_encoding job failling in e2e OMR workflow--problem could be related to Fast_Pixelwise job

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Rodan#768]
This is the traceback:

File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/Rodan/rodan/jobs/base.py", line 773, in run
    retval = self.run_my_task(inputs, settings, arg_outputs)
  File "/code/Rodan/rodan/jobs/MEI_encoding/MEI_encoding.py", line 85, in run_my_task
    mei_string = bm.process(jsomr, syls, classifier_table, width_mult, width_container)
  File "/code/Rodan/rodan/jobs/MEI_encoding/build_mei_file.py", line 654, in process
    meiDoc = build_mei(pairs, classifier, width_container, jsomr['staves'], jsomr['page'])
  File "/code/Rodan/rodan/jobs/MEI_encoding/build_mei_file.py", line 450, in build_mei
    bb = staves[0]['bounding_box']
IndexError: list index out of range

I tried two different folios, 245r and 245v, with the same result. This is the image file:
![Einsiedeln__Stiftsbibliothek__Codex_611_245r](https://user-images.githubusercontent.com/83373378/190142256-83d84e4a-80e9-4111-8535-bd46c036e3bd.jpg)

I think the problem might be with the Fast_Pixelwise_Analysis job, because both the staff layer and symbol layer it outputs are almost empty. These are the relevant files for 245r:
https://drive.google.com/drive/folders/1skMW8QpLpl-8HgvS6jIu8GffLUA1LCiB?usp=sharing

**Comment by softcat477** [comment]
Hello, Can you show me the workflow and resources you're using? This is to make sure we can recreate this issue in production.

**Comment by JoyfulGen** [comment]
This is the workflow:
<img width="1202" alt="Screen Shot 2022-09-15 at 1 22 38 PM" src="https://user-images.githubusercontent.com/83373378/190393174-4e6cfb61-d006-479e-bc7e-063f95fad42b.png">

There are two empty input puts for the non-interactive classifier because I use the feature selection tool. I've added that file to the resources below.

Here are all the resources:
https://drive.google.com/drive/folders/1pQd5Yc7XyNKbOy3Ph1Tb-G_nWJKi_d3S?usp=sharing

**Comment by JoyfulGen** [comment]
Welp, this isn't an issue after all. Turns out a lot of my uploaded and generated resources have the same names, so I assigned the wrong ones... my bad. Apologies for the false alarm! Closing issue now.
