### ISSUE TITLE
Not able to export workflows

### ISSUE THREAD

**Issue by martha-thomae** [DDMAL/Rodan#770]
The button for exporting a workflow (shown in the next screenshot) is not working. 

![Screen Shot 2022-09-15 at 3 48 03 PM](https://user-images.githubusercontent.com/13948831/190925614-f0ddf491-2d98-4b0f-9138-56a9053d2cc2.png)

When opening the developer tools, it shows the following message:

![Screen Shot 2022-09-15 at 3 50 17 PM](https://user-images.githubusercontent.com/13948831/190925619-27899a78-51f8-4e1f-8e87-df38d040e799.png)

**This functionality of exporting a workflow is very useful, as one can export the workflow, send the file to someone else, and this second person can import the workflow to their own project in Rodan to use it for their own purposes.**

**Comment by sabrina0822** [comment]
I fixed this issue and have merged the changes to develop. Need to do a new production release for the changes to show up
