### ISSUE TITLE
List of project users is incomplete - Impossible to share project with users outside of list

### ISSUE THREAD

**Issue by martha-thomae** [DDMAL/Rodan#771]
In Rodan, you have the chance to share your project with different users (so they can both see and run workflows in that project). You do this by clicking on the project, then clicking on the `Users` button, and then using the dropdown menu of the `Project Users` window to select the user you want to share your project with. However, f**or some reason, the dropdown menu doesn't show all the users in Rodan right now. Could someone check out why it doesn't load all users?**

-----

Process to share a project with other users:

1. Click on the project and on the `Users` button
<img width="652" alt="Screen Shot 2022-09-18 at 3 47 53 PM" src="https://user-images.githubusercontent.com/13948831/190925757-0a519f0c-ee5f-49fc-8d2c-255adcfbe7d2.png">

2. This opens the `Project Users` window3. 
<img width="987" alt="Screen Shot 2022-09-18 at 3 48 43 PM" src="https://user-images.githubusercontent.com/13948831/190925804-891a6d4f-acf8-40e4-858e-5bd4cd33571e.png">

3. Select the user from the dropdown menu list
<img width="964" alt="Screen Shot 2022-09-18 at 3 48 50 PM" src="https://user-images.githubusercontent.com/13948831/190925819-305a9877-b3ce-45e4-90b8-312de88a5e84.png">

**Comment by sabrina0822** [comment]
My first instinct with this was to check the postgres database to see if all the users are there, if so then it's an issue with rodan otherwise a postgres one.
However, I think that the name of the database has changed in one of the pull requests as when I do psql -U rodan (which used to work), I get the error: FATAL:  role "rodan" does not exist.
Going to look into this more

**Comment by martha-thomae** [comment]
This issue still needs to be resolved. Any ideas, @sabrina0822 or @malajvan or @softcat477 ?

**Comment by sabrina0822** [comment]
I haven't had a chance to look at this more but last I checked with @cadagong and oddly enough all the users are showing up in the frontend and apparently there is a scroll bar option so I'm not fully sure what is going on there. 
I personally don't have a ton of experience with frontend to know exactly what is going on but I might work with David soon to see if he has any ideas.

**Comment by cadagong** [comment]
@sabrina0822 and I took a look at this issue today. We weren't able to solve it just yet, but it doesn't appear to be a front-end issue, so we're slowly eliminating possible causes. Will be investigating over the next few days!
