### ISSUE TITLE
rodan-main/celery/py3-celery containers can't pass health check

### ISSUE THREAD

**Issue by softcat477** [DDMAL/Rodan#797]
Docker kills and restarts the container whenever a container fails to pass its health check multiple times in a roll. This results in hanging jobs (https://github.com/DDMAL/Rodan/issues/779#issuecomment-1285627116) and missing resources when uploading multiple resources.

## Missing resources: Steps to recreate this issue
1. Upload 28 images at once (`32.5MB x 4`, `24.6MB x 4`, `31.9MB x 4`, `28MB x 4`, `52.6MB x 4`, `4.5MB x 4`, `30.4MB x 4`).
2. Go to staging, `docker ps` and see `rodan-main` or `celery` being restarted.
3. Open syslog, find messages showing that containers are restarted because they fail passing their health check.
4. This happens from time to time. If it does happen, you only get 20~22 resources on rodan.

## Hanging jobs: Steps to recreate this issue
1. Upload 28 images at once (`32.5MB x 4`, `24.6MB x 4`, `31.9MB x 4`, `28MB x 4`, `52.6MB x 4`, `4.5MB x 4`, `30.4MB x 4`).
2. Use this workflow (Convert image to png), sign all resources to the input port.
![Screen Shot 2022-10-26 at 1 39 23 PM](https://user-images.githubusercontent.com/25975988/198097544-e631e5a2-72b2-42d3-8900-d6cdc7467331.png)
3. Run the workflow. Some jobs run successfully, and others just hang there. 
![Screen Shot 2022-10-26 at 1 40 47 PM](https://user-images.githubusercontent.com/25975988/198097944-2b70ceb7-1a5e-49f7-b642-c7c587480399.png)
4. Go to staging, `docker ps`. See `celery` or `py3-celery` container are restarted.

**Comment by timothydereuse** [comment]
my first thought: Does this only happen when you're trying to upload 28 images all at once? Do things work fine if you upload them in batches, wait for all the jobs to finish, and then run the PNG jobs?

I will find a way to double-check what is happening to the celery jobs that is making them unhealthy. Is it an out-of-memory error?

**Comment by softcat477** [comment]
1. it runs at most six jobs at a time, each job processes one image.
2. it's not an oom error, there's no oom message in `syslog`
