### ISSUE TITLE
Question: what is expected to slow rodan down?

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Rodan#812]
I'm not always 100% sure if a behaviour I notice in rodan is supposed to happen or not. Here's a list of behaviours I've noticed; I'd love to know which of these are normal and expected (apologies if these are obvious):

- Rodan slows down if I try to run two workflows at once
- Rodan slows down if I use the internet for something else
- The workflow hangs and never finishes if I close my laptop
- The workflow hangs and never finishes if I disconnect from the internet
- When running a big job, the "pending requests" counter goes wayyyyy up (see example below)
<img width="1436" alt="Request counter bonkers" src="https://user-images.githubusercontent.com/83373378/201350577-85c98bd8-a6f1-4b06-ae9d-6870d3247aa9.png">

Once I know which, if any, of these behaviours aren't supposed to happen, I'll make separate issues for them.
@timothydereuse

**Comment by timothydereuse** [comment]
- Running two workflows at once is likely going to make Rodan slow down at least a little; those workflows are competing for resources behind the scenes, so it makes sense
- This one is possible, but it depends on what exactly is slower. Just the UI itself and uploading/downloading resources? That would make sense. Shouldn't have an impact on how long a job takes to finish.
- Turning off your laptop / disconnecting from the internet _should_ have absolutely no effect on whether or not a job finishes; those are all being run way in the backend, in totally separate docker containers. So, if this is happening consistently, something's super messed up. I'm not even sure what it would be. Maybe it is actually finishing but the browser client is never getting updated for some reason?
- The "pending request" thing has been a known issue for a while. Whenever a request is dropped or not received by Rodan it just never stops counting them. I think there's an issue for that that's been up for years.

**Comment by softcat477** [comment]
duplicated issue
Any additional slow-down/latency issues should be reported here: #827
