### ISSUE TITLE
Automatically detect number of pixels between staff lines in un-layer-separated manuscript images

### ISSUE THREAD

**Issue by timothydereuse** [DDMAL/Rodan#846]
There should be a Rodan job that operates on a manuscript image before any other processing has been applied to it. It should take in the image alone and output a single value: the factor that you must rescale the image by in order to make the distance between staff lines to equal 64 pixels (on average). Doesn't have to be perfect but should not depend on the characteristics / colors of any single manuscript. The image resizing job should be able to take this value as an input.

This is necessary before layer separation has been performed so that the separation can happen on the smaller, resized image.

**Comment by MrMondrian** [comment]
fixed by https://github.com/DDMAL/Rodan/pull/1040
