### ISSUE TITLE
File type not correct when uploading .csv resource

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/Rodan#872]
In Rodan client, whenever a user uploads a .csv file to their resources, the default file type for the file ends up being `application/octet-stream ()`. The user then needs to manually go and change the file type to `text/csv`. Ideally, the proper file type would be selected by default.

**Comment by jacobdgm** [comment]
Tagging @martha-thomae to verify my summary, and/or add further details.

**Comment by martha-thomae** [comment]
Yes, this issue happens consistently with all `csv` files. It is one instance where rodan cannot correctly identify the resource type (`text/csv`) and assigns its default (`appilcation/octet-stream`). Thanks, Jacob!

**Comment by PythonSemicolon** [comment]
#911
