### ISSUE TITLE
[Interactive Classifier] Group all selected load times

### ISSUE THREAD

**Issue by MrMondrian** [DDMAL/Rodan#887]
When using the group all selected feature, interactive classifier sometimes loads for a very long time, and sometimes the loading never completes. This may be related to the other latency issues we are seeing on rodan.

**Comment by malajvan** [comment]
Can you tell us the steps to reproduce this issue? Also, did you encounter this on staging, production, locally, or all of them?

**Comment by MrMondrian** [comment]
It was happening on production. This issue did not occur on staging for the last E2E.
