### ISSUE TITLE
rodan-rabbitmq-1 container throws errors

### ISSUE THREAD

**Issue by MrMondrian** [DDMAL/Rodan#930]
The rodan-rabbitmq-1 container started throwing errors for me on Tuesday. I initially ignored it because our ssl expired that day and figured it could be related somehow. However after that was fixed, the issue did not go away. @sabrina0822 also saw this error on her machine.
![Screenshot from 2023-06-01 09-39-15](https://github.com/DDMAL/Rodan/assets/57821698/ff13e610-780b-484a-a9c2-330b5490abcd)

**Comment by softcat477** [comment]
mime throws the same error but it still works

**Comment by softcat477** [comment]
![image](https://github.com/DDMAL/Rodan/assets/25975988/a02d56dc-bbd4-4933-86b2-d7fa604918d1)
