### ISSUE TITLE
Makefile run_arm issue

### ISSUE THREAD

**Issue by jackyyzhang03** [DDMAL/Rodan#937]
In `run_arm`, the `docker compose` command is invalid. It should be `docker compose -f arm-compose.yml up`, but is instead `docker compose up -f arm-compose.yml up` (extra up before -f flag).

**Comment by malajvan** [comment]
Can you tell me where this issue is? I'm in `develop` and it seems fine. Please correct me if I'm at the wrong place
<img width="741" alt="image" src="https://github.com/DDMAL/Rodan/assets/64571718/a84d57f7-0e16-4311-95eb-e8a830bd12e4">

**Comment by jackyyzhang03** [comment]
You might have to pull the most recent changes. I believe it was changed in #933.
![IMG_6816](https://github.com/DDMAL/Rodan/assets/81784897/76afd45b-02a7-432b-ac83-ebcf727a5799)

**Comment by malajvan** [comment]
oops my bad. @softcat477  made the change so I'll leave the rest for her. Thanks!
