### ISSUE TITLE
3 OMR functions performing less well (May to October comparison) - 3/3 SYLLABLES

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Rodan#945]
This is one of three issues related to a significant change in OMR performance between May and October 2022. 
1/3 Bounding boxes: https://github.com/DDMAL/Rodan/issues/802
2/3 Pitch finding: https://github.com/DDMAL/Rodan/issues/944

This issue is about syllables.

I've noticed that in recent OMR runs, the syllables are too few and too big. To test this theory, I ran Einsie folio 129r yesterday (October 27) to compare the result to my initial processing of the same folio on May 30. 

Here's a comparison of the results with the syllable highlight (I only resized the staves to make the pitches easy to see; I made no other changes):
<img width="817" alt="Syllables comparison 129r" src="https://user-images.githubusercontent.com/83373378/198675841-64b2ae4d-9160-4c57-9dcf-6639c5425d73.png">

You can see that the syllables in the recent folio are generally too big. There are also parts of the text missing and some syllables are empty right off the bat.

These are the two MEI files, as well as the original folio image:
[129r now.mei.zip](https://github.com/DDMAL/Rodan/files/9889843/129r.now.mei.zip)
[129r then.mei.zip](https://github.com/DDMAL/Rodan/files/9889844/129r.then.mei.zip)
![Einsiedeln__Stiftsbibliothek__Codex_611_129r](https://user-images.githubusercontent.com/83373378/198676093-ec6b8ac8-998f-4280-be78-224beb9c9065.jpg)

**Comment by MrMondrian** [comment]
@JoyfulGen is this issue still a problem?

**Comment by JoyfulGen** [comment]
@MrMondrian it looks like syllable groupings are back to what they used to be! Thanks for the heads-up, I'll close the issue now.
