### ISSUE TITLE
Neon background image doesn't always show up (and there are no error messages).

### ISSUE THREAD

**Issue by cadagong** [DDMAL/Rodan#954]

**Comment by malajvan** [comment]
Steps to Reproduce:
(This only happens in Firefox browser)
1. Upload a jpg image on to Rodan, manually change the resource's type to `image/rgb+png` and press `Save`. 
2. Input the image onto `PNG (RGB)` job. 
3. Use the output of the job above as input for `Neon`. 
4. Open `Neon` interactive in a pop up
--> Image doesn't load, no apparent Error thrown.

If anyone encounters the same issue with a DIFFERENT method (ie. different browser, different job output, different initial image resource type etc.) please let us know. From my understanding this doesn't cause an issue in Chrome or Safari.
