### ISSUE TITLE
Centering with ctrl-0 on workflow builder does not work on firefox

### ISSUE THREAD

**Issue by MrMondrian** [DDMAL/Rodan#993]
A feature to recenter the screen around the jobs using ctrl-0 was added to the workflow builder. This does not work on firefox when run locally.

**Comment by jackyyzhang03** [comment]
Works on my feature branch (`jacky/workflow-builder-enhancement`) so it seems something was lost during or after merging.

**Comment by jackyyzhang03** [comment]
Somehow this appears to have been caused by #942.
