### ISSUE TITLE
docker compose is not working on staging

### ISSUE THREAD

**Issue by softcat477** [DDMAL/Rodan#997]
`docker compose pull` is not working on staging because of the docker version, and it breaks the `make pull` command, which is required to deploy staging.

**Comment by malajvan** [comment]
Is it this issue or related to this? https://github.com/docker/compose/issues/8630

**Comment by softcat477** [comment]
Fixed by following this: https://github.com/docker/compose/tree/v2#linux
1. download [docker-compose-linux-x86_64](https://github.com/docker/compose/releases/download/v2.19.0/docker-compose-linux-x86_64)
2. make it executable.
3. move it to `/root/.docker/cli-plugins` and `/usr/libexec/docker/cli-plugins`
